### ISSUE TITLE
npm run build doesn't work

### ISSUE THREAD

**Issue by VChertukhin** [jaredpalmer/razzle#1043]
Hello, dear developers of razzle! I've just created new app with "create-razzle-app my-app" command, and "npm start" works pretty well, however, I tried to create build of this app (I didn't change anything, only razzle-generated app) and got this:

vchertukhin@MSI:/mnt/d/dev/avtoemali/new_site/avtoemali-frontend$ npm run build
> my-razzle-app@0.1.0 build /mnt/d/dev/avtoemali/new_site/avtoemali-frontend
> razzle build
Creating an optimized production build...
Compiling client...
/mnt/d/dev/avtoemali/new_site/avtoemali-frontend/node_modules/razzle/scripts/build.js:10
  throw err;
  ^

Error: original.line and original.column are not numbers -- you probably meant to omit the original mapping entirely and only map the generated position. If so, pass null for the original mapping instead of an object with empty or null values.
    at SourceMapGenerator_validateMapping [as _validateMapping] (/mnt/d/dev/avtoemali/new_site/avtoemali-frontend/node_modules/webpack-sources/node_modules/source-map/lib/source-map-generator.js:276:15)
    at SourceMapGenerator_addMapping [as addMapping] (/mnt/d/dev/avtoemali/new_site/avtoemali-frontend/node_modules/webpack-sources/node_modules/source-map/lib/source-map-generator.js:110:12)
    at /mnt/d/dev/avtoemali/new_site/avtoemali-frontend/node_modules/webpack-sources/node_modules/source-map/lib/source-map-generator.js:72:17
    at Array.forEach (<anonymous>)
    at BasicSourceMapConsumer.SourceMapConsumer_eachMapping [as eachMapping] (/mnt/d/dev/avtoemali/new_site/avtoemali-frontend/node_modules/webpack-sources/node_modules/source-map/lib/source-map-consumer.js:157:14)
    at Function.SourceMapGenerator_fromSourceMap [as fromSourceMap] (/mnt/d/dev/avtoemali/new_site/avtoemali-frontend/node_modules/webpack-sources/node_modules/source-map/lib/source-map-generator.js:48:24)
    at SourceMapSource.node (/mnt/d/dev/avtoemali/new_site/avtoemali-frontend/node_modules/webpack-sources/lib/SourceMapSource.js:32:35)
    at SourceMapSource.proto.sourceAndMap (/mnt/d/dev/avtoemali/new_site/avtoemali-frontend/node_modules/webpack-sources/lib/SourceAndMapMixin.js:30:18)
    at getTaskForFile (/mnt/d/dev/avtoemali/new_site/avtoemali-frontend/node_modules/webpack/lib/SourceMapDevToolPlugin.js:37:30)
    at files.forEach (/mnt/d/dev/avtoemali/new_site/avtoemali-frontend/node_modules/webpack/lib/SourceMapDevToolPlugin.js:136:20)
    at Array.forEach (<anonymous>)
    at compilation.hooks.afterOptimizeChunkAssets.tap (/mnt/d/dev/avtoemali/new_site/avtoemali-frontend/node_modules/webpack/lib/SourceMapDevToolPlugin.js:130:12)
    at SyncHook.eval [as call] (eval at create (/mnt/d/dev/avtoemali/new_site/avtoemali-frontend/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:7:1)
    at SyncHook.lazyCompileHook (/mnt/d/dev/avtoemali/new_site/avtoemali-frontend/node_modules/tapable/lib/Hook.js:154:20)
    at hooks.optimizeChunkAssets.callAsync.err (/mnt/d/dev/avtoemali/new_site/avtoemali-frontend/node_modules/webpack/lib/Compilation.js:1315:42)
    at _promise1.then._result1 (eval at create (/mnt/d/dev/avtoemali/new_site/avtoemali-frontend/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:14:1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! my-razzle-app@0.1.0 build: `razzle build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the my-razzle-app@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/vchertukhin/.npm/_logs/2019-06-30T13_00_28_898Z-debug.log

**Comment by sergiopellegrini** [comment]
@VChertukhin @jaredpalmer A bug in terser 4.0.1 which was released hours ago.

A few packages like Gatsby and Vue CLI are having the same issue. 

Here are the related issues and conversations.

https://github.com/gatsbyjs/gatsby/issues/15249
https://twitter.com/kylemathews/status/1145161508147486721
https://github.com/vuejs/vue-cli/issues/4210

Suggested temporary fix:

For npm users: run npm i terser@4.0.0
For yarn users: add the following field to package.json and then rerun yarn:

```
"resolutions": {
  "terser": "4.0.0"
}
```

**Comment by VChertukhin** [comment]
Thanks!
