### ISSUE TITLE
Unable to build when using aws-amplify-react

### ISSUE THREAD

**Issue by HazemMhiri** [jaredpalmer/razzle#1111]
## Expected Behavior
I expect my app to build both in dev and in production.

## Current Behavior
Build fails with both razzle start and razzle build.

## Steps to Reproduce
1. install and import aws-amplify-react

## Detailed Description
Here is the error trace:
````
PROJECT_DIR/node_modules/@aws-amplify/ui/dist/style.css:13
:root {
^

SyntaxError: Unexpected token :
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (PROJECT_DIR/node_modules/aws-amplify-react/src/Amplify-UI/Amplify-UI-Components-React.jsx:5:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
````

**Comment by tiagobbraga** [comment]
The same

**Comment by nimaa77** [comment]
I saw the same issue in #1070, can anyone create a sample repo for this. so we can find and fix the problem easier?

**Comment by nimaa77** [comment]
let's move all conversations to that issue so we have everything in one place.

I'm going to close this.
