### ISSUE TITLE
razzle and serverless-http

### ISSUE THREAD

**Issue by nicholasess** [jaredpalmer/razzle#1113]
Hello Everyone
I'm trying to work my application with serverless-http, but I don't found a solution for that.
After run command ```yarn build```, is created a folder called ```build``` and a file ```server.js```, but if I use the server.js as reference, the serverlerss-offline show errors as:

```
TypeError: Cannot read property 'callback' of undefined
    at getFramework (/Users/nicholas/divid-new/node_modules/serverless-http/lib/framework/get-framework.js:16:18)
    at module.exports (/Users/nicholas/divid-new/node_modules/serverless-http/serverless-http.js:14:21)
```

Do you have any ideas?

**Comment by jgcmarins** [comment]
how did you solve?
