### ISSUE TITLE
npm install react-bootstrap bootstrap breaks app with webpack errors.

### ISSUE THREAD

**Issue by laurencefass** [jaredpalmer/razzle#1126]
ive installed razzle as per simple npx and npm install instructions.

initial config working fine apart from hot module reload not working and i raised separate issue for this.

with the module installed i want to npm install modules... to start i tried to **npm i react-bootstrap  bootstrap** and the app is broken on restart.

npm start reports errors after installing the above modules.

```
1|razzle   | ✅  Server-side HMR Enabled!
1|razzle   | 🚀 started
1|razzle   | ℹ Compiling Server
1|razzle   | ✔ Server: Compiled with some errors in 853.93ms
1|razzle   | 🔁  HMR Reloading `./server`...
1|razzle   | [HMR] Updated modules:
1|razzle   | [HMR]  - ./node_modules/css-loader/lib/css-base.js
1|razzle   | [HMR]  - ./src/Home.css
1|razzle   | [HMR]  - ./src/App.css
1|razzle   | [HMR]  - ./src/App.js
1|razzle   | [HMR]  - ./src/server.js
1|razzle   | [HMR]  - ./src/Home.js
1|razzle   | [HMR] Update applied.
1|razzle   | ℹ Compiling Server
1|razzle   | ✔ Server: Compiled with some errors in 64.20ms

/root/.pm2/logs/razzle-error.log last 15 lines:
1|razzle   |     at __webpack_require__ (/app/razzle/razzle/webpack/bootstrap:685:1)
1|razzle   |     at fn (/app/razzle/razzle/build/webpack:/webpack/bootstrap:59:1)
1|razzle   |     at Object../src/Home.css (/app/razzle/razzle/build/webpack:/src/Home.js:10:1)
1|razzle   |     at __webpack_require__ (/app/razzle/razzle/build/webpack:/webpack/bootstrap:685:1)
1|razzle   |     at fn (/app/razzle/razzle/build/webpack:/webpack/bootstrap:59:1)
1|razzle   |     at Module../src/Home.js (/app/razzle/razzle/build/webpack:/src/Home.js:18:1)
1|razzle   |     at __webpack_require__ (/app/razzle/razzle/build/webpack:/webpack/bootstrap:685:1)
1|razzle   |     at fn (/app/razzle/razzle/build/webpack:/webpack/bootstrap:59:1)
1|razzle   |     at Module../src/App.js (/app/razzle/razzle/build/server.js:1063:63)
1|razzle   | [HMR] Cannot apply update.
1|razzle   | [HMR] Aborted because ./node_modules/webpack/hot/poll.js?300 is not accepted
1|razzle   | Update propagation: ./node_modules/webpack/hot/poll.js?300 -> 0
1|razzle   |     at hotApply (/app/razzle/razzle/webpack/bootstrap:434:1)
1|razzle   |     at /app/razzle/razzle/build/webpack:/webpack/bootstrap:272:1
1|razzle   | [HMR] You need to restart the application!

```

the same (standard) npm install process worked fine with CRA and next applications with no errors.

am i npm installing correctly? is there a special way of installing modules? thanks.

**Comment by laurencefass** [comment]
i restart the application and get the following errors:

```
1|razzle   |
1|razzle   | > my-razzle-app@0.1.0 start /app/razzle/razzle
1|razzle   | > PORT=3100 razzle start
1|razzle   |
1|razzle   |  WAIT  Compiling...
1|razzle   |
1|razzle   | ℹ Compiling Client
1|razzle   | ℹ ｢wds｣: Project is running at http://localhost:3101/
1|razzle   | ℹ ｢wds｣: webpack output is served from undefined
1|razzle   | ℹ ｢wds｣: Content not from webpack is served from /app/razzle/razzle
1|razzle   | ℹ ｢wds｣: 404s will fallback to /index.html

1|razzle  | ✔ Client: Compiled successfully in 11.23s
1|razzle  | ℹ Compiling Server
1|razzle  | ✔ Server: Compiled with some errors in 569.64ms
1|razzle  | Warning: Please use `require("react-router-dom").Route` instead of `require("react-router-dom/Route")`. Support for the latter will be removed in the next major release.
1|razzle  | Warning: Please use `require("react-router-dom").Switch` instead of `require("react-router-dom/Switch")`. Support for the latter will be removed in the next major release.
1|razzle  | /app/razzle/razzle/build/server.js:1321
1|razzle  | !(function webpackMissingModule() { var e = new Error("Cannot find module 'express'"); e.code = 'MODULE_NOT_FOUND'; throw e; }());
1|razzle  |                                             ^
1|razzle  | Cannot find module 'express'
1|razzle  |   1319 | /* harmony import */ var react_router_dom__WEBPACK_IMPORTED_MODULE_2__ = __webpack_require__(/*! react-router-dom */ "react-router-dom");
1|razzle  |   1320 | /* harmony import */ var react_router_dom__WEBPACK_IMPORTED_MODULE_2___default = /*#__PURE__*/__webpack_require__.n(react_router_dom__WEBPACK_IMPORTED_MODULE_2__);
1|razzle  | > 1321 | !(function webpackMissingModule() { var e = new Error("Cannot find module 'express'"); e.code = 'MODULE_NOT_FOUND'; throw e; }());
1|razzle  |   1322 | /* harmony import */ var react_dom_server__WEBPACK_IMPORTED_MODULE_4__ = __webpack_require__(/*! react-dom/server */ "react-dom/server");
1|razzle  |   1323 | /* harmony import */ var react_dom_server__WEBPACK_IMPORTED_MODULE_4___default = /*#__PURE__*/__webpack_require__.n(react_dom_server__WEBPACK_IMPORTED_MODULE_4__);
1|razzle  |   1324 | var _jsxFileName = "/app/razzle/razzle/src/server.js";
1|razzle  |     at webpackMissingModule (/app/razzle/razzle/build/server.js:1321:45)
1|razzle  |     at Module../src/server.js (/app/razzle/razzle/build/server.js:1321:127)
1|razzle  |     at __webpack_require__ (/app/razzle/razzle/webpack/bootstrap:685:1)
1|razzle  |     at fn (/app/razzle/razzle/build/webpack:/webpack/bootstrap:59:1)
1|razzle  |     at Module../src/index.js (/app/razzle/razzle/build/webpack:/src/index.js:3:1)
1|razzle  |     at __webpack_require__ (/app/razzle/razzle/build/webpack:/webpack/bootstrap:685:1)
1|razzle  |     at fn (/app/razzle/razzle/build/webpack:/webpack/bootstrap:59:1)
1|razzle  |     at Object.0 (/app/razzle/razzle/build/server.js:1369:18)
1|razzle  |     at __webpack_require__ (/app/razzle/razzle/build/webpack:/webpack/bootstrap:685:1)
1|razzle  |     at /app/razzle/razzle/build/webpack:/webpack/bootstrap:752:1
```

also why does it say: "webpack output is served from undefined?"

**Comment by laurencefass** [comment]
should i be using yarn to install dependencies and packages?
