### ISSUE TITLE
Cannot find module 'css-loader/locals'

### ISSUE THREAD

**Issue by Anthodpnt** [jaredpalmer/razzle#1138]
Hey guys,

I'm getting an error when running Razzle inside an existing CRA project...

- I have installed `razzle` and `razzle-plugin-scss` as `devDependencies`
- I have created a `razzle-config.js` file to extend defaults.
- I have updated the `npm-scripts` in the `package.json` file to call `razzle` commands

However, every time `razzle start` runs, I get the following error:

```
Error: Cannot find module 'css-loader/locals'
Require stack:
- /Users/bulldog/Sites/B/BETR/node_modules/razzle-plugin-scss/index.js
- /Users/bulldog/Sites/B/BETR/node_modules/razzle/config/runPlugin.js
- /Users/bulldog/Sites/B/BETR/node_modules/razzle/config/createConfig.js
- /Users/bulldog/Sites/B/BETR/node_modules/razzle/scripts/start.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:713:15)
    at Function.resolve (internal/modules/cjs/helpers.js:74:19)
    at module.exports (/Users/bulldog/Sites/B/BETR/node_modules/razzle-plugin-scss/index.js:106:31)
    at runPlugin (/Users/bulldog/Sites/B/BETR/node_modules/razzle/config/runPlugin.js:26:10)
    at /Users/bulldog/Sites/B/BETR/node_modules/razzle/config/createConfig.js:549:16
    at Array.forEach (<anonymous>)
    at module.exports (/Users/bulldog/Sites/B/BETR/node_modules/razzle/config/createConfig.js:548:13)
    at main (/Users/bulldog/Sites/B/BETR/node_modules/razzle/scripts/start.js:48:22)
    at processTicksAndRejections (internal/process/task_queues.js:85:5) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/bulldog/Sites/B/BETR/node_modules/razzle-plugin-scss/index.js',
    '/Users/bulldog/Sites/B/BETR/node_modules/razzle/config/runPlugin.js',
    '/Users/bulldog/Sites/B/BETR/node_modules/razzle/config/createConfig.js',
    '/Users/bulldog/Sites/B/BETR/node_modules/razzle/scripts/start.js'
  ]
}
```

Looking at a solution to get rid of this error, I found [**this issue**](https://github.com/webpack-contrib/css-loader/issues/897) from the `css-loader` repository. There seems to be an `onlyLocals` [**option**](https://github.com/webpack-contrib/css-loader#onlylocals) that can be enabled/disabled. I was thinking that this would have resolved the error but unfortunately, I still get it whether I set this option to `true` or `false` in `razzle-plugin-scss` options.

Here is more details of the current setup:

**razzle-config.js**
```js
module.exports = {
  plugins: [
    {
      name: 'scss',
      options: {
        css: {
          dev: {
            modules: false,
            sourceMap: true,
            onlyLocals: true,
            importLoaders: 1
          },
          prod: {
            modules: false,
            minimize: true,
            sourceMap: false,
            onlyLocals: true,
            importLoaders: 1
          },
        }
      },
    }
  ],
  modify: (config) => {
    // Resolve Paths
    config.resolve.modules = [
      '.',
      'src',
      'src/pages',
      'src/routes',
      'src/contexts',
      'src/components',
      'node_modules'
    ];

    // Resolve Extensions
    config.resolve.extensions = [
      '.js',
      '.jsx',
      '.css',
      '.scss',
      '.sass'
    ];

    return config;
  }
};
```

**package.json**
```json
{
  "name": "@betr/client",
  "version": "1.0.0",
  "license": "MIT",
  "dependencies": {},
  "scripts": {
    "test": "react-app-rewired test",
    "start": "razzle start",
    "build": "razzle build",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "browserslist": {
    "production": [
      "> 0.25%",
      "edge >= 14",
      "not ie <= 10",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version",
      "last 1 edge version",
      "last 1 ie version"
    ]
  },
  "devDependencies": {
    "razzle": "^3.0.0",
    "razzle-plugin-scss": "^3.0.0"
  }
}
```

Thank you for your time!

Best regards,
Anthodpnt

**Comment by adamthewan** [comment]
Same here. Seems like it's fixed in a PR here: https://github.com/jaredpalmer/razzle/pull/1033
But it's not updated on NPM unfortunately.

**Comment by adamthewan** [comment]
@Anthodpnt I managed to get it working by editing the `razzle-plugin-scss` src file and loading into `razzle.config.js` like so:

```

module.exports = {
  plugins: [RazzleSCSS],
};
```

**Comment by dnaranjo89** [comment]
Try removing your `node_modules` and `package-lock.json` and then `npm install` again

**Comment by cotwitch** [comment]
`yarn upgrade` fixed it for me.
