### ISSUE TITLE
unable to render simple route in default create-razzle-app.

### ISSUE THREAD

**Issue by laurencefass** [jaredpalmer/razzle#1157]
i am unable to render a simple route in the default create-razzle-app.

i have modified the default main.js file to include a Router, but this reports an error: 

```
Invariant failed: Browser history needs a DOM

  1337 |         }
  1338 |       }, react__WEBPACK_IMPORTED_MODULE_5___default.a.createElement("a", {
> 1339 |         href: "https://palmer.chat",
  1340 |         __source: {
  1341 |           fileName: _jsxFileName,
  1342 |           lineNumber: 68

    at invariant (/app/razzle/razzle/node_modules/tiny-invariant/dist/tiny-invariant.cjs.js:13:11)
    at Object.createHistory [as createBrowserHistory] (/app/razzle/razzle/node_modules/history/cjs/history.js:273:16)
    at new BrowserRouter (/app/razzle/razzle/node_modules/react-router-dom/modules/BrowserRouter.js:11:13)
    at processChild (/app/razzle/razzle/node_modules/react-dom/cjs/react-dom-server.node.development.js:3161:14)
    at resolve (/app/razzle/razzle/node_modules/react-dom/cjs/react-dom-server.node.development.js:3126:5)
    at ReactDOMServerRenderer.render (/app/razzle/razzle/node_modules/react-dom/cjs/react-dom-server.node.development.js:3600:22)
    at ReactDOMServerRenderer.read (/app/razzle/razzle/node_modules/react-dom/cjs/react-dom-server.node.development.js:3538:29)
    at renderToString (/app/razzle/razzle/node_modules/react-dom/cjs/react-dom-server.node.development.js:4247:27)
    at /app/razzle/razzle/build/server.js:1339:87
    at Layer.handle [as handle_request] (/app/razzle/razzle/node_modules/express/lib/router/layer.js:95:5)
```

modified main.js looks like this.

```
import React from 'react';
import logo from './react.svg';
import './Home.css';
import {
  BrowserRouter as Router,
  Switch,
  Route,
  Link,
} from "react-router-dom";

function RoutingExample() {
  return (
    <div>
    <h1>Routing Example</h1>
    <Router>
      <div>
        <ul>
          <li>
            <Link to="/">Home</Link>
          </li>
          <li>
            <Link to="/about">About</Link>
          </li>
        </ul>
        <Switch>
          <Route exact path="/">
            <Home />
          </Route>
          <Route path="/about">
            <About />
          </Route>
        </Switch>
      </div>
    </Router>
    </div>
  );
}

function About() {
  return (
    <div>
      <h2>About</h2>
    </div>
  );
}

export class Home extends React.Component {
  render() {
    return (
      <div className="Home">
        <RoutingExample></RoutingExample>
        <div className="Home-header">
          <img src={logo} className="Home-logo" alt="logo" />
          <h2>Welcome to Razzle</h2>
        </div>
        <p className="Home-intro">
          To get started, edit <code>src/App.js</code> or{' '}
          <code>src/Home.js</code> and save to reload.
        </p>
        <ul className="Home-resources">
          <li>
            <a href="https://github.com/jaredpalmer/razzle">Docs</a>
          </li>
          <li>
            <a href="https://github.com/jaredpalmer/razzle/issues">Issues</a>
          </li>
          <li>
            <a href="https://palmer.chat">Community Slack</a>
          </li>
        </ul>
      </div>
    );
  }
}

```

client.js unchanged remains as installed.

any help or guidance much appreciated.

thanks

**Comment by aswin-s** [comment]
You will need a StaticRouter for SSR.  The way I've solved it is that for SSR, I've below code in server.js

```jsx
<StaticRouter context={context} location={req.url}>
  <App />
</StaticRouter>
```

And for client replace that with BrowserRouter in client.js
```jsx
hydrate(
  <BrowserRouter>
      <App />
  </BrowserRouter>,
  document.getElementById('root')
)
```

**Comment by laurencefass** [comment]
solution was as simple as adding `<switch>` in `<App>` in App.js and Links work from any component.

```
const App = () => (
  <div>
    <Switch>
      <Route exact path="/" component={Home} />
      <Route exact path="/about" component={About} />
      <Route exact path="/article" component={Article} />
      <Route exact path="/page" component={Page} />
      <Route exact path="/summary" component={Summary} />
      <Route exact path="/detail" component={Detail} />
    </Switch>
  </div>
);
```
