### ISSUE TITLE
after js example wth reverse proxy gives module errors - HMR looks broken.

### ISSUE THREAD

**Issue by laurencefass** [jaredpalmer/razzle#1175]
ive installed the module with curl and yarn installed. ive also added razzle-plugin-proxy to reverse proxy behind nginx.

nginx config
```
    # after.js (based on razzle.js)
    location ^~ /after-dev/webpack/sockjs-node/ { 
        proxy_pass http://0.0.0.0:3011/sockjs-node/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }     
    location ^~ /after-dev/webpack/ {
        proxy_pass http://0.0.0.0:3011/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }      	
    location /after-dev/ {
        proxy_pass http://0.0.0.0:3010/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
```
.env file
```
# dev mode with path
PUBLIC_PATH='https://razzle.syntapse.co.uk/after-dev/'
CLIENT_PUBLIC_PATH='https://razzle.syntapse.co.uk/after-dev/webpack/'
PORT=3010

# production mode with path (run with start:prod)
# PUBLIC_PATH=https://apps.syntapse.co.uk/razzle-prod/
# PORT=3012
```

yarn start
```
$ razzle start
 WAIT  Compiling...


✖ Client
  Compiled with some errors in 5.31s

◯ Server


✖ ｢wdm｣: Hash: 374b22757024169a5a3c
Version: webpack 4.41.4
Time: 5311ms
Built at: 12/21/2019 11:45:06 AM
                          Asset      Size  Chunks                   Chunk Names
           static/js/0.chunk.js  33.3 KiB       0  [emitted]
       static/js/0.chunk.js.map  34.9 KiB       0  [emitted] [dev]
           static/js/1.chunk.js  9.48 KiB       1  [emitted]
       static/js/1.chunk.js.map  4.48 KiB       1  [emitted] [dev]
           static/js/2.chunk.js    12 KiB       2  [emitted]
       static/js/2.chunk.js.map   4.2 KiB       2  [emitted] [dev]
            static/js/bundle.js  2.43 MiB  client  [emitted]        client
        static/js/bundle.js.map   2.7 MiB  client  [emitted] [dev]  client
static/media/react.9a28da9f.svg  7.72 KiB          [emitted]
Entrypoint client = static/js/bundle.js static/js/bundle.js.map
[1] multi (webpack)-dev-server/client?http://razzle.syntapse.co.uk (webpack)/hot/dev-server.js ./node_modules/razzle-dev-utils/webpackHotDevClient.js ./src/client 64 bytes {client} [built]
[./node_modules/@jaredpalmer/after/build/index.js] 417 bytes {client} [built]
[./node_modules/process/browser.js] 5.29 KiB {client} [built]
[./node_modules/razzle-dev-utils/node_modules/sockjs-client/lib/entry.js] 244 bytes {client} [built]
[./node_modules/razzle-dev-utils/node_modules/strip-ansi/index.js] 150 bytes {client} [built]
[./node_modules/razzle-dev-utils/webpackHotDevClient.js] 7.74 KiB {client} [built]
[./node_modules/react-dev-utils/formatWebpackMessages.js] 4.27 KiB {client} [built]
[./node_modules/react-dev-utils/launchEditorEndpoint.js] 330 bytes {client} [built]
[./node_modules/react-dom/index.js] 1.33 KiB {client} [built]
[./node_modules/react-error-overlay/lib/index.js] 341 KiB {client} [built]
[./node_modules/react-router-dom/es/index.js] 1010 bytes {client} [built]
[./node_modules/react/index.js] 190 bytes {client} [built]
[./node_modules/webpack-dev-server/client/index.js?http://razzle.syntapse.co.uk] (webpack)-dev-server/client?http://razzle.syntapse.co.uk 4.29 KiB {client} [built]
[./node_modules/webpack/hot/dev-server.js] (webpack)/hot/dev-server.js 1.59 KiB {client} [built]
[./src/client.js] 719 bytes {client} [built]
    + 191 hidden modules

ERROR in (webpack)-dev-server/client/utils/createSocketUrl.js
Module build failed (from ./node_modules/string-replace-loader/index.js):
Error: Replace failed (strict mode) : var\ sockPath\ \=\ '\/sockjs\-node'; → var sockPath = '/after-dev/webpack/sockjs-node';
    at replace (/app/razzle/with-afterjs/node_modules/string-replace-loader/lib/replace.js:17:11)
    at Object.processChunk (/app/razzle/with-afterjs/node_modules/string-replace-loader/lib/processChunk.js:11:17)
 @ (webpack)-dev-server/client?http://razzle.syntapse.co.uk 20:22-56
 @ multi (webpack)-dev-server/client?http://razzle.syntapse.co.uk (webpack)/hot/dev-server.js ./node_modules/razzle-dev-utils/webpackHotDevClient.js ./src/client

✖ Client
  Compiled with some errors in 5.31s

✔ Server
  Compiled successfully in 292.98ms

✅  Server-side HMR Enabled!
> Started on port 3010
```

**Comment by laurencefass** [comment]
client js 
```
...
ensureReady(routes).then(data =>
  hydrate(
    <BrowserRouter basename="/after-dev">
      <After data={data} routes={routes} />
    </BrowserRouter>,
    document.getElementById('root')
  )
);

if (module.hot) {
  module.hot.accept();
}

```

**Comment by nimaa77** [comment]
What is the problem here, I can't get your question :)

I used after.js behind a proxy and it's working without any problems

**Comment by fivethreeo** [comment]
I think my hacky plugin had something to do with this. Solved better by my autodetect sockJs options. Also devServer.public should be mentioned in docs. he is trying to serve at a subpath of the domain possibly at another port. devServer.public combined with autodetected sockJs options + correct CLIENT_PUBLIC_PATH would make this simple.

**Comment by nimaa77** [comment]
@fivethreeo I don't get it, so I won't close this.
when you got the access to repo just do the thing you think is the best

about the socket.js thing check #885 I did something with that ...
and could you please do a code review on that too

**Comment by fivethreeo** [comment]
Just close this or change the title. The error is unrelated, belongs in my plugins issues.
