### ISSUE TITLE
not able to use react-native-paper

### ISSUE THREAD

**Issue by devgeeksclub** [jaredpalmer/razzle#1190]
I am using razzle with typescript and react-native-web. every thing is working fine. But when I install react-native-paper and followed the instructor here  
[https://callstack.github.io/react-native-paper/using-on-the-web.html](url)

and then when I run
`yarn start`

I got this error

```
Cannot find module 'react-native'
Require stack:
- /Users/username/Code/allTest/with-typescript/node_modules/react-native-paper/lib/commonjs/styles/fonts.js
- /Users/username/Code/allTest/with-typescript/node_modules/react-native-paper/lib/commonjs/styles/DefaultTheme.js
- /Users/username/Code/allTest/with-typescript/node_modules/react-native-paper/lib/commonjs/core/theming.js
- /Users/username/Code/allTest/with-typescript/node_modules/react-native-paper/lib/commonjs/index.js
- /Users/username/Code/allTest/with-typescript/build/server.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:954:17)
    at Function.Module._load (internal/modules/cjs/loader.js:847:27)
    at Module.require (internal/modules/cjs/loader.js:1016:19)
    at require (internal/modules/cjs/helpers.js:69:18)
    at Object.<anonymous> (/Users/username/Code/allTest/with-typescript/node_modules/react-native-paper/lib/commonjs/styles/fonts.tsx:1:1)
    at Module._compile (internal/modules/cjs/loader.js:1121:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1160:10)
    at Module.load (internal/modules/cjs/loader.js:976:32)
    at Function.Module._load (internal/modules/cjs/loader.js:884:14)
    at Module.require (internal/modules/cjs/loader.js:1016:19)
```

I think the problem only occur on server side , not client side. 
any workaround or advice to do with razzle.config.js

**Comment by fivethreeo** [comment]
React-native makes no sense in server side rendering. Try using the new spa mode in 3.1.0
