### ISSUE TITLE
This is where the problem is, it can't be solved. Good sad

### ISSUE THREAD

**Issue by Elliotlong** [jaredpalmer/razzle#1195]
λ node server
internal/modules/cjs/loader.js:984
  throw err;
  ^

Error: Cannot find module 'console-stamp'
Require stack:
- C:\Users\Administrator\shopify-monitor\server.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:981:15)
    at Function.Module._load (internal/modules/cjs/loader.js:863:27)
    at Module.require (internal/modules/cjs/loader.js:1043:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (C:\Users\Administrator\shopify-monitor\server.js:1:1)
    at Module._compile (internal/modules/cjs/loader.js:1157:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1177:10)
    at Module.load (internal/modules/cjs/loader.js:1001:32)
    at Function.Module._load (internal/modules/cjs/loader.js:900:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ 'C:\\Users\\Administrator\\shopify-monitor\\server.js' ]
}

**Comment by jgcmarins** [comment]
can we close this one?
