### ISSUE TITLE
the loadable-components is reporting an error when run with razzle-plugin-proxy 

### ISSUE THREAD

**Issue by laurencefass** [jaredpalmer/razzle#1197]
im trying out the loadable components example. it loads ok but HMR is broken. i see error:

```
Uncaught Error: Module build failed (from ./node_modules/string-replace-loader/index.js):
Error: Replace failed (strict mode) : var\ sockPath\ \=\ '\/sockjs\-node'; → var sockPath = '/loadable/webpack/sockjs-node';
    at replace (/app/razzle/loadable/node_modules/string-replace-loader/lib/replace.js:17)
    at Object.processChunk (/app/razzle/loadable/node_modules/string-replace-loader/lib/processChunk.js:11)
    at Object../node_modules/webpack-dev-server/client/utils/createSocketUrl.js (socket.js:52)
    at __webpack_require__ (bootstrap:768)
    at fn (bootstrap:129)
    at Object.<anonymous> (client:20)
    at Object../node_modules/webpack-dev-server/client/index.js?http://razzle.syntapse.co.uk (client:176)
    at __webpack_require__ (bootstrap:768)
    at fn (bootstrap:129)
    at Object.1 (client.js:13)
    at __webpack_require__ (bootstrap:768)
    at bootstrap:906
```
the console reports error also:

```
247|razzle-loadable  | ERROR in (webpack)-dev-server/client/utils/createSocketUrl.js
247|razzle-loadable  | Module build failed (from ./node_modules/string-replace-loader/index.js):
247|razzle-loadable  | Error: Replace failed (strict mode) : var\ sockPath\ \=\ '\/sockjs\-node'; → var sockPath = '/loadable/webpack/sockjs-node';
247|razzle-loadable  |     at replace (/app/razzle/loadable/node_modules/string-replace-loader/lib/replace.js:17:11)
247|razzle-loadable  |     at Object.processChunk (/app/razzle/loadable/node_modules/string-replace-loader/lib/processChunk.js:11:17)
247|razzle-loadable  |  @ (webpack)-dev-server/client?http://razzle.syntapse.co.uk 20:22-56
247|razzle-loadable  |  @ multi (webpack)-dev-server/client?http://razzle.syntapse.co.uk (webpack)/hot/dev-server.js ./node_modules/razzle-dev-utils/webpackHotDevClient.js ./src/client

```

my razzle.config.js:
```
'use strict';

module.exports = {
  modify(config, { target, dev }, webpack) {
    const appConfig = config;
    if ( target==='web' && dev ) {
      appConfig.devServer.sockPath = "/loadable/sockjs-node/";
    }
    return appConfig;
  },
  plugins: ['proxy'],
};
```
.env file:
```
PUBLIC_PATH='https://razzle.syntapse.co.uk/loadable/'
CLIENT_PUBLIC_PATH='https://razzle.syntapse.co.uk/loadable/webpack/'
PORT=3070
```

I have installed the razzle-plugin-proxy so it may be an issue with this and not core Razzle but i don't know for sure. I'm using the exact same .env and razzle.config.js i use for other examples which working ok.

I can leave it running here: https://razzle.syntapse.co.uk/loadable/

any advice appreciated

thanks

**Comment by fivethreeo** [comment]
update razzle-plugin proxy now, did some investegations. Had to do with unpinned webpack-dev-server in razzle and my oversight. Also a docfix to  the nginx config.

**Comment by fivethreeo** [comment]
loadable-components also does not play well with HMR, adding module.hot.accept() to each lazy loaded module may help

**Comment by nimaa77** [comment]
I'm going to close this issue if you think it's a mistake just reopen it
