### ISSUE TITLE
Issue using typescript for a firebase deployment

### ISSUE THREAD

**Issue by arunmenon1975** [jaredpalmer/razzle#1201]
I am in the process of building my first SSR app with `Typescript`.  I am also using `redux` for state management. It did require some research and after various attempts I somehow was not getting everything working alright. Until i found Razzle. Solved all my initial problems. I have my simple example SSR app running on Typescript with Redux. 

Until i attempted to integrate `Firebase`. 

I get the following errors when i atempt a `Yarn serve` (from the script `"serve": "firebase serve",`):

```
=== Serving from '/Users/arunmenon/Sites/clones/with-typescript'...

⚠  Your functions directory does not specify a Node version.
   - Learn more at https://firebase.google.com/docs/functions/manage-functions#set_runtime_options
✔  functions: functions emulator started at http://localhost:5001
i  functions: Watching "/Users/arunmenon/Sites/clones/with-typescript" for Cloud Functions...
i  hosting: Serving hosting files from: build/public
✔  hosting: Local server: http://localhost:5000
⚠  Error: Cannot find module '/Users/arunmenon/Sites/clones/with-typescript'
Require stack:
- /Users/arunmenon/.nvm/versions/node/v13.9.0/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:980:15)
    at Function.Module._load (internal/modules/cjs/loader.js:862:27)
    at Module.require (internal/modules/cjs/loader.js:1040:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at /Users/arunmenon/.nvm/versions/node/v13.9.0/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:719:33
    at Generator.next (<anonymous>)
    at fulfilled (/Users/arunmenon/.nvm/versions/node/v13.9.0/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
⚠  We were unable to load your functions code. (see above)
   - It appears your code is written in Typescript, which must be compiled before emulation.
   - You may be able to run "npm run build" in your functions directory to resolve this.

```

I dont have a `functions` directory since i use the Firebase example provided in this repo as the base. I have all the requisite imports in my `package.json` . 

My `server.tsx` file:

```
import App from '../common/containers/App';
import configureStore from '../common/redux/store/configureStore';
import express from 'express';
import * as functions from 'firebase-functions';

import { Provider } from 'react-redux';
import React from 'react';
import { fetchCounter } from '../common/api/counter';
import qs from 'qs';
import { renderToString } from 'react-dom/server';
import serialize from 'serialize-javascript';

import { StateNavigator } from 'navigation';
import { NavigationHandler } from 'navigation-react';
import Isomorphic from '../client/Isomorphic';
import getStateNavigator from '../common/getStateNavigator';

const assets = require(process.env.RAZZLE_ASSETS_MANIFEST || '');

const server = express();

server
  .disable('x-powered-by')
  .use(express.static(process.env.RAZZLE_PUBLIC_DIR || '/'))
  .get ('/*', async (req, res) => {
    const stateNavigator = await getStateNavigator();
    const { state, data } = stateNavigator.parseLink(req.url);
    const url = stateNavigator.fluent()
        .navigate('people')
        .navigate(state.key, data).url;
    stateNavigator.start(url);
    fetchCounter((apiResult: number) => {
      // Read the counter from the request, if provided
      const params = qs.parse(req.query);
      const counter = parseInt(params.counter, 10) || apiResult || 0;

      // Compile an initial state
      const preloadedState = { counter };

      // Create a new Redux store instance
      const store = configureStore(preloadedState);

      // Render the component to a string
      const markup = renderToString(
        <Provider store={store}>
            <NavigationHandler stateNavigator={stateNavigator}>
                <App />
            </NavigationHandler>
        </Provider>
      );

      // Grab the initial state from our Redux store
      const finalState = store.getState();
      const html = `<!doctype html>
      <html lang="">
      <head>
          <meta http-equiv="X-UA-Compatible" content="IE=edge" />
          <meta charSet='utf-8' />
          <title>Razzle Redux Example</title>
          <meta name="viewport" content="width=device-width, initial-scale=1">
          ${assets.client.css
            ? `<link rel="stylesheet" href="${assets.client.css}">`
            : ''}
            ${process.env.NODE_ENV === 'production'
              ? `<script src="${assets.client.js}" defer></script>`
              : `<script src="${assets.client.js}" defer crossorigin></script>`}
      </head>
      <body>
          <div id="root">${markup}</div>
          <script>
            window.__PRELOADED_STATE__ = ${serialize(finalState)}
          </script>
      </body>
  </html>`;
      res.set('Cache-Control', 'public, max-age=600,s-maxage=1200');
     // res.send(finalHtml);
      res.send(html);
    });
  });

export default server; //tried with the below as well
//export let menuappssr = functions.https.onRequest(server);

```

**Comment by arunmenon1975** [comment]
This turns out to be a non-issue after all and more of a dev mistake/oversight. i did not update `razzle.config` with the required entries. There are some other issues(most likely similar mistakes) but the core issue is resolved so i am closing this now.
