### ISSUE TITLE
Razzle not accepting array of child routes.

### ISSUE THREAD

**Issue by akif-ih** [jaredpalmer/razzle#1207]
I made routes thing generic and when i pass array of routes after reading them from config it will throw below error
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
    at ReactDOMServerRenderer.render (/Users/akif/Documents/code/test-razzle/node_modules/react-dom/cjs/react-dom-server.node.development.js:3743:1)
    at ReactDOMServerRenderer.read (/Users/akif/Documents/code/test-razzle/build/webpack:/node_modules/react-dom/cjs/react-dom-server.node.development.js:3373:1)
    at renderToString (/Users/akif/Documents/code/test-razzle/build/webpack:/node_modules/react-dom/cjs/react-dom-server.node.development.js:3988:1)
    at /Users/akif/Documents/code/test-razzle/build/webpack:/src/server.js:21:1
    at Layer.handle [as handle_request] (/Users/akif/Documents/code/test-razzle/build/webpack:/node_modules/express/lib/router/layer.js:95:1)
    at next (/Users/akif/Documents/code/test-razzle/build/webpack:/node_modules/express/lib/router/route.js:137:1)
    at Route.dispatch (/Users/akif/Documents/code/test-razzle/build/webpack:/node_modules/express/lib/router/route.js:112:1)
    at Layer.handle [as handle_request] (/Users/akif/Documents/code/test-razzle/build/webpack:/node_modules/express/lib/router/layer.js:95:1)
    at /Users/akif/Documents/code/test-razzle/build/webpack:/node_modules/express/lib/router/index.js:281:1
    at param (/Users/akif/Documents/code/test-razzle/build/webpack:/node_modules/express/lib/router/index.js:354:1)

import React from 'react'
import { Route, Switch } from 'react-router-dom'
import PrivateRoute from './PrivateRoute'

import { routes } from "../route-definitions"
import Home from "../Home";

let appRoutes = (() => (
    routes.map(route => (
        route.map(routeDef => {
            const Component = routeDef.type === 'PRIVATE' ? PrivateRoute : Route
            return  <Component {...routeDef.props}/>
        })
    ))
))().flat()
const Routes = () => <Switch>{appRoutes}</Switch>

export default Routes

**Comment by akif-ih** [comment]
Issue resolved issue is in my code which is due some wrong route.
