### ISSUE TITLE
Importing npm package results in error unless modifying config.externals

### ISSUE THREAD

**Issue by Joelgullander** [jaredpalmer/razzle#1243]
Could anyone explain to me what goes wrong or right here? 

Basicly I am trying to import a npm package that got both /esm & /cjs build files. The following error appears on yarn start:

```
Cannot find module '@xxxx/buttons'
Require stack:
- /Users/xxxx/xxxx/xxxx/xxx.Client/build/server.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
    at Function.Module._load (internal/modules/cjs/loader.js:690:27)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.@xxxx/buttons (/Users/xxx/xxx/xx/xx.xx/external "@xxxx/buttons":1:1)
    at __webpack_require__ (/Users/xx/xx/xx/xx.Client/build/webpack:/webpack/bootstrap:684:1)
    at fn (/Users/xx/dynamicdog/xx/xx.Client/build/webpack:/webpack/bootstrap:59:1)
    at Module../src/common/Home.tsx (/Users/xxx/xxx/xxxx/xxxx.Client/build/webpack:/src/common/Home.tsx:2:1)
    at __webpack_require__ (/Users/xxx/xxx/xxx/xxx.Client/build/webpack:/webpack/bootstrap:684:1)
    at fn (/Users/xxxx/xxx/xxx/xxxx.Client/build/webpack:/webpack/bootstrap:59:1)
```

When adding the following webpack overrule the error is gone:

```
module.exports = {
  plugins: [
    'typescript',
  ],
  modify: (config, { target, dev }, webpack) => {
    delete config.externals;
    return config
    ......
    ......

```

The package.json for the /buttons package:

```
{
  "name": "@xxxx/buttons",
  "version": "0.1.4",
  "description": "",
  "module": "esm/index.js",
  "types": "esm/index.d.ts",
  "author": "xxxx.se",
  "license": "MIT",
  "scripts": {
    "clean": "rimraf ./esm && rimraf ./cjs",
    "prebuild": "yarn clean",
    "build": "yarn build:esm && yarn build:cjs",
    "build:esm": "tsc -p tsconfig.build.json --module esnext --outDir esm --declarationDir esm",
    "build:cjs": "tsc -p tsconfig.build.json --module commonjs --outDir cjs --declarationDir cjs",
    "test": "mocha \"test/**/*.spec.ts?(x)\"",
    "start": "webpack-dev-server --mode development --progress --open",
    "prepack": "yarn build"
  },
  "dependencies": {
    "@xxxx/theme": "^0.1.3"
  },
  "peerDependencies": {
    "react": ">=16",
    "react-dom": ">=16",
    "styled-components": "^5.1.0"
  },
  "files": [
    "esm",
    "cjs",
    "src"
  ],
  "gitHead": "c9cfe9574ec6ca4ba5e22cc145678c3def71c95c"
}
```

**Comment by Joelgullander** [comment]
FYI: @xxx/buttons is my own package so I just need some further explanation on what's wrong and I can fix it myself. I have no idea as to why this is happening though.

**Comment by fivethreeo** [comment]
It is because razzle won’t build anything in node_modules. You need to whitelist anything razzle needs to drop into to build. Set main to the cjs build of the module.

**Comment by Joelgullander** [comment]
Thanks @fivethreeo it worked.
