### ISSUE TITLE
Error with loadable-stats.json with yarn export on 3.3.0-canary5

### ISSUE THREAD

**Issue by smcyr** [jaredpalmer/razzle#1411]
### Current Behavior
If I do a `yarn export` on Windows, it gives me this error:
```
  throw err;
  ^

Error: ENOENT: no such file or directory, open 'C:\Projects\test\web\build\public\C:\Projects\test\web\build\public\loadable-stats.json'
    at Object.openSync (fs.js:458:3)
    at Object.readFileSync (fs.js:360:35)
    at C:\Projects\test\web\node_modules\razzle-dev-utils\FileSizeReporter.js:42:33
    at Array.map (<anonymous>)
    at C:\Projects\test\web\node_modules\razzle-dev-utils\FileSizeReporter.js:41:10
    at Array.map (<anonymous>)
    at printFileSizesAfterBuild (C:\Projects\test\web\node_modules\razzle-dev-utils\FileSizeReporter.js:37:6)
    at C:\Projects\test\web\node_modules\razzle\scripts\export.js:56:11 {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: 'C:\\Projects\\test\\web\\build\\public\\C:\\Projects\\test\\web\\build\\public\\loadable-stats.json'
}
```

### Expected behavior

It shouldn't give an error. 

### Reproducible example

Try static export on a Windows machine.

### Suggested solution(s)

There is probably a need to normalize paths somewhere for Windows, for razzle-dev-utils.

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Razzle           | 3.3.0-canary.5
| Node             | v12.18.1
| npm/Yarn         | Yarn 1.22.4
| Operating System | Windows 10

**Comment by fivethreeo** [comment]
Seems to come from loadable. Post your server.js

**Comment by smcyr** [comment]
Here it is:
```javascript
import path from 'path';
import Application from 'src/ui/application';
import React from 'react';
import express, {Request} from 'express';
import {ChunkExtractor, ChunkExtractorManager} from '@loadable/server';
import {StaticRouter, StaticRouterContext, Route} from 'react-router';
import initializeApollo from 'src/initializers/apollo/server';
import {ApolloProvider} from '@apollo/client';
import {renderToStringWithData} from '@apollo/client/react/ssr';
import i18nextMiddleware from 'i18next-express-middleware';
import {I18nextProvider} from 'react-i18next';
import {sanitizeLanguage} from 'src/utils/sanitize-language';
import document from './document';
import initializeI18next from 'src/initializers/i18next/server';
import {QueryParamProvider} from 'use-query-params';
import {HelmetProvider} from 'react-helmet-async';
import compression from 'compression';
import basicAuth from 'express-basic-auth';
import cacheControl from 'express-cache-controller';
import forceSSL from 'express-force-ssl';
import forceDomain from 'forcedomain';
import * as Sentry from '@sentry/node';
import getEnv, {asBoolean, asInteger} from 'src/utils/get-env';
import initializeSentry from 'src/initializers/sentry/server';
import redirection from 'src/services/redirection';
import shortcuts from 'src/services/shortcuts';
import getSitemap from 'src/services/sitemap';

const HEALTH_STATUS_CODE = 200;
const ASSETS_MAX_AGE = asInteger(getEnv('ASSETS_MAX_AGE'));
const PAGES_MAX_AGE = asInteger(getEnv('PAGES_MAX_AGE'));
const SITEMAP_MAX_AGE = asInteger(getEnv('SITEMAP_MAX_AGE'));
const CANONICAL_HOST = getEnv('CANONICAL_HOST');
const FORCE_SSL = asBoolean(getEnv('FORCE_SSL'));
const BASIC_AUTH_USERNAME = getEnv('BASIC_AUTH_USERNAME');
const BASIC_AUTH_PASSWORD = getEnv('BASIC_AUTH_PASSWORD');

const stringifyState = (state: any) => {
  return JSON.stringify(state)
    .replace(/</g, '\\u003c')
    .replace(/'/g, `\\'`)
    .replace(/\\"/g, '\\\\"');
};

initializeSentry();
const i18next = initializeI18next();
const server = express();

server.disable('x-powered-by');

server.use(Sentry.Handlers.requestHandler());

server.get('/health', (_, response) => response.sendStatus(HEALTH_STATUS_CODE));

server.use(redirection);

server.use(shortcuts);

server.use(compression());

server.get('/sitemap.xml', async (_, response, next) => {
  try {
    const sitemap = await getSitemap();

    response.header('Content-Type', 'application/xml');

    if (SITEMAP_MAX_AGE) {
      response.header('Cache-Control', `max-age=${SITEMAP_MAX_AGE}`);
    }

    response.status(200);
    response.send(sitemap);
  } catch (error) {
    next(error);
  }
});

server.use(
  express.static(process.env.RAZZLE_PUBLIC_DIR!, {
    maxAge: ASSETS_MAX_AGE !== null ? ASSETS_MAX_AGE * 1000 : undefined
  })
);

if (CANONICAL_HOST) {
  server.use(forceDomain({hostname: CANONICAL_HOST}));
}

if (FORCE_SSL) {
  server.set('forceSSLOptions', {trustXFPHeader: true, httpsPort: 443});
  server.use(forceSSL);
}

if (BASIC_AUTH_USERNAME && BASIC_AUTH_PASSWORD) {
  const options = {
    challenge: true,
    users: {
      [BASIC_AUTH_USERNAME]: BASIC_AUTH_PASSWORD
    }
  };

  server.use(basicAuth(options));
}

server.use(Sentry.Handlers.errorHandler());

server.use(i18nextMiddleware.handle(i18next, {removeLngFromUrl: false}));

server.get('/', (request, response) => {
  const language = sanitizeLanguage(request.language);
  return response.redirect(301, `/${language}`);
});

function isPreview(request: Request) {
  const [, search = ''] = request.originalUrl.split('?');

  return search.includes('x-craft-live-preview=');
}

const cacheRequestHandler = cacheControl({maxAge: PAGES_MAX_AGE});
const noCacheRequestHandler = cacheControl({
  noCache: true,
  maxAge: 0,
  noStore: true,
  mustRevalidate: true
});

server.use((request, response, next) => {
  if (!PAGES_MAX_AGE || isPreview(request)) {
    noCacheRequestHandler(request, response, next);
  } else {
    cacheRequestHandler(request, response, next);
  }
});

export const renderApp = async (request: Request) => {
  const apollo = initializeApollo(isPreview(request));

  const statsFile = path.resolve('./build/loadable-stats.json');
  const extractor = new ChunkExtractor({
    statsFile,
    entrypoints: ['client']
  });
  const routerContext: StaticRouterContext = {};
  const helmetContext: any = {};
  const html = await renderToStringWithData(
      <ChunkExtractorManager extractor={extractor}>
        <HelmetProvider context={helmetContext}>
          <StaticRouter location={request.url} context={routerContext}>
            <QueryParamProvider ReactRouterRoute={Route}>
              <ApolloProvider client={apollo}>
                <I18nextProvider i18n={request.i18n}>
                  <Application />
                </I18nextProvider>
              </ApolloProvider>
            </QueryParamProvider>
          </StaticRouter>
        </HelmetProvider>
      </ChunkExtractorManager>
  );

  const apolloState = stringifyState(apollo.extract());
  const scripts = extractor.getScriptTags({crossorigin: true});
  const links = extractor.getLinkTags({crossorigin: true});
  const styles = extractor.getStyleTags({crossorigin: true});
  const language = request.language;
  const i18nState = stringifyState(
      request.i18n.languages.reduce((memo, language) => {
        memo[language] = request.i18n.services.resourceStore.data[language];
        return memo;
      }, {})
  );
  const env = stringifyState(
      Object.keys(process.env).reduce((memo, key) => {
        if (key.startsWith('RAZZLE')) {
          memo[key] = process.env[key];
        }

        return memo;
      }, {})
  );

  const doc = document({
    helmet: helmetContext.helmet,
    gtmId: process.env.RAZZLE_GTM_ID,
    scripts,
    links,
    styles,
    apolloState,
    html,
    language,
    i18nState,
    env
  });

  return {
    html: doc,
    routerContext: routerContext
  };
};

server.get('/:lng*', async (request, response, next) => {
  try {
    const { html, routerContext } = await renderApp(request);

    if (routerContext.url) {
      return response.redirect(301, routerContext.url);
    }

    if (routerContext.statusCode) {
      response.status(routerContext.statusCode);
    }

    response.send(html);
  } catch (error) {
    next(error);
  }
});

export default server;
```

**Comment by fivethreeo** [comment]
Sorry, I meant static_export.js

**Comment by fivethreeo** [comment]
But i think it is this.

```js
const statsFile = path.resolve('./build/loadable-stats.json');
```

**Comment by smcyr** [comment]
I did a console.log of that and it returns `C:\Projects\test\web\build\public\loadable-stats.json` when I do the `yarn export`. I'm not sure why it prepends `C:\Projects\test\web\build\public\` on export. It works fine for the `yarn start` / `yarn build`.

Here is my `static_export.js` file:
```javascript
import { renderApp } from './server';
import i18next from 'i18next';
import { i18nOptions } from './initializers/i18next/server';
import { sanitizeLanguage } from './utils/sanitize-language';

export const render = async (req, res) => {
  const lng = sanitizeLanguage(req.url.replace(/^\/+/, '').substring(2, 0));
  const i18n = i18next.createInstance();

  await i18n.init({...i18nOptions, lng: lng});

  req.originalUrl = req.url;
  req.i18n = i18n;
  req.language = i18n.language;
  req.languages = i18n.languages;

  const { html } = await renderApp(req);

  res.json({ html });
};

export const routes = () => {
  return ['/en', '/fr'];
};
```

**Comment by fivethreeo** [comment]
https://stackoverflow.com/questions/32514900/using-nodes-path-resolve-on-windows

**Comment by fivethreeo** [comment]
You are sure the loadable-stats.json exists ?

**Comment by smcyr** [comment]
I found the fix:
https://github.com/jaredpalmer/razzle/pull/1416
You need to use `path.sep` instead of '/' for Windows in the `export.js`

**Comment by fivethreeo** [comment]
You may be right that this should be changed but I don’t quite get why these issues are related?

**Comment by fivethreeo** [comment]
If you just don’t use / or sep at all does that work too? I see build has no sep.

**Comment by fivethreeo** [comment]
Oh, I see now. But still, does it work without any sep?

**Comment by fivethreeo** [comment]
Fixed in canary and finch branch

**Comment by daniellizik** [comment]
@smcyr how did you get `@sentry/node` to work in `server.js`? i keep getting
```
TypeError: mod.require is not a function
```
could you please post the code you have in
```
import initializeSentry from 'src/initializers/sentry/server';
```
sentry repo doesn't offer much advice on how to integrate with universal apps, specifically razzle https://github.com/getsentry/sentry-javascript/issues/951
