### ISSUE TITLE
SyntaxError: Unexpected token 'export' When Referencing a TS Project from Same Monorepo

### ISSUE THREAD

**Issue by thefringeninja** [jaredpalmer/razzle#1463]
Minimal Reproduction is here: https://github.com/thefringeninja/razzle-repro/

Seeing this when running `razzle start` on my project - a typescript react library compiled with `tsc` and an app compiled with `razzle`, using `razzle@4.0.0-canary.7`. `razzle build` seems to work just fine. I assume I need to do something to my `razzle.config.js` but I'm not sure what it is! Any help would be greatly appreciated.
```
yarn run v1.22.5
$ razzle start
 WAIT  Compiling...


✔ Client
  Compiled successfully in 1.11s

✔ Server
  Compiled successfully in 129.62ms

/home/jwow/dev/razzle-repro/package/tslib/src/index.js:2
export default x;
^^^^^^

SyntaxError: Unexpected token 'export'
    at wrapSafe (internal/modules/cjs/loader.js:979:16)
    at Module._compile (internal/modules/cjs/loader.js:1027:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.@test/tslib (/home/jwow/dev/razzle-repro/package/app/external "/home/jwow/dev/razzle-repro/node_modules/@test/tslib/src/index.js":1:1)
    at __webpack_require__ (/home/jwow/dev/razzle-repro/package/app/build/webpack:/webpack/bootstrap:748:1)
    at fn (/home/jwow/dev/razzle-repro/package/app/build/webpack:/webpack/bootstrap:59:1)

sswp> !!! script exited with code 1
sswp> !!! Script did not load, or HMR failed; not restarting

```

**Comment by fivethreeo** [comment]
In tsconfig.json

```json
{
  "compilerOptions" : {
    "paths" : {
      "tslib/*": "package/tslib/src/*"
    }
  }
}
```
