### ISSUE TITLE
How can I ask Razzle to show the line number

### ISSUE THREAD

**Issue by cskeogh** [jaredpalmer/razzle#1652]
### Current Behavior

SyntaxError: Unexpected token 'export'

```shell
$ yarn start
yarn run v1.22.5
warning ..\package.json: No license field
$ razzle start
If you have issues with css make sure postcss resolves to v8.2.4.
See: https://razzlejs.org/getting-started#common-issues

CssMinimizerPlugin currently uses clean-css,
we will switch to cssnano once it supports postcss v8.2.4.

 WAIT  Compiling...


√ Client
  Compiled successfully in 2.67s

√ Server
  Compiled successfully in 279.91ms

C:\Users\craig\Projects\node_modules\entity-decode\browser.js:8
export default function decode(html) {
^^^^^^

SyntaxError: Unexpected token 'export'
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1025:15)
    at Module._compile (node:internal/modules/cjs/loader:1059:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1124:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:816:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at Object.entity-decode/browser (C:\Users\craig\Projects\node_modules\mermaid\dist\webpack:\mermaid\external "entity-decode\browser":1:1)
    at __webpack_require__ (C:\Users\craig\Projects\node_modules\mermaid\dist\webpack:\mermaid\webpack\bootstrap:19:1)
sswp> !!! Script exited with code 1
```

### Expected behavior

Server starts.

### Reproducible example

```shell
$ yarn create razzle-app razzle-mermaid-fail
$ yarn add mermaid
```
Edit `src\Home.js` and import mermaid.

```javascript
import React from 'react';
import logo from './react.svg';
import './Home.css';
import mermaid from 'mermaid';

class Home extends React.Component {
  render() {
    mermaid.initialize();
    return (
      <div className="Home">
...
```

### Additional context

This probably isn't a Razzle bug but I can't work out how to solve. Any help would be most welcome. Thank you,

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Razzle           | 4.0.5 |
| Razzle Plugins   | None |
| Node             | 16.4.0 |
| Browser          | Chrome |
| npm/Yarn         | yarn |
| Operating System | Windows 10 |
| TypeScript       | no |
| React            | 17.0.2 |

**Comment by cskeogh** [comment]
A working workaround is:
```javascript
import mermaid from '../node_modules/mermaid/dist/mermaid';
```
instead of:
```javascript
import mermaid from 'mermaid';
```
I don't understand why.

**Comment by fivethreeo** [comment]
https://razzlejs.org/docs/customization#transpilation-of-external-modules

**Comment by cskeogh** [comment]
Thank you for the pointer. I now get a different error. A TypeError in `mermaid.core.js`. Perhaps mermaid is the fault. How can I ask Razzle to show the line number in `mermaid.core.js`?

With a razzle.config.js:

```javascript
// razzle.config.js
'use strict';
module.exports = {
  modifyWebpackOptions({
    env: {
      target, // the target 'node' or 'web'
      dev, // is this a development build? true or false
    },
    options: {
      webpackOptions, // the default options that will be used to configure webpack/ webpack loaders and plugins
    }
  }) {
    webpackOptions.notNodeExternalResMatch = (request, context) => {
       return /mermaid/.test(request)
    };
    webpackOptions.babelRule.include = webpackOptions.babelRule.include.concat([
      /mermaid/
    ]);
    return webpackOptions;
  },
  options: {
    verbose: true, // set to true to get more info/error output
    debug: { // debug flags
      options: false, // print webpackOptions that will be used in webpack config
      config: false, // print webpack config
      nodeExternals: true // print node externals debug info 
    },
  }
};
```

```shell
$ yarn start
yarn run v1.22.5
$ razzle start
If you have issues with css make sure postcss resolves to v8.2.4.
See: https://razzlejs.org/getting-started#common-issues

CssMinimizerPlugin currently uses clean-css,
we will switch to cssnano once it supports postcss v8.2.4.

 WAIT  Compiling...

sswp> Type `rs<Enter>` to restart the worker

× Client
  Compiled with some errors in 2.96s

( ) Server


i ｢wds｣: Project is running at http://localhost:3001/
i ｢wds｣: webpack output is served from http://localhost:3001/
i ｢wds｣: Content not from webpack is served from C:\Users\craig\Projects\razzle-mer-fail
i ｢wds｣: 404s will fallback to /index.html
Not externalizing C:\Users\craig\Projects\razzle-mer-fail\node_modules\razzle-dev-utils\prettyNodeErrors.js (relative require)
Not externalizing C:\Users\craig\Projects\razzle-mer-fail\node_modules\webpack\hot\poll.js?300 (relative require)
Not externalizing C:\Users\craig\Projects\razzle-mer-fail\src (relative require)
Not externalizing !!C:\Users\craig\Projects\razzle-mer-fail\node_modules\razzle-start-server-webpack-plugin\dist\monitor-loader.js!C:\Users\craig\Projects\razzle-mer-fail\node_modules\razzle-start-server-webpack-plugin\dist\monitor-loader.js (cannot resolve)

× Client
  Compiled with some errors in 2.96s

* Server █████████████████████████ building (10%) 1/2 modules 1 active

× Client
  Compiled with some errors in 2.96s

* Server █████████████████████████ building (12%) 19/20 modules 1 active
 babel-loader » src\Home.js

Not externalizing fs (default)
Externalizing jest-message-util (node_modules)
Externalizing @babel/code-frame (node_modules)
Not externalizing ./log (relative require)
Not externalizing ./log-apply-result (relative require)
Externalizing webpack/hot/log-apply-result (node_modules)

× Client
  Compiled with some errors in 2.96s

* Server █████████████████████████ building (13%) 25/25 modules 0 active


Not externalizing fs (default)
Externalizing jest-message-util (node_modules)
Externalizing @babel/code-frame (node_modules)
Not externalizing ./log (relative require)
Not externalizing ./log-apply-result (relative require)
Externalizing webpack/hot/log-apply-result (node_modules)
Not externalizing ./log (relative require)
Externalizing express (node_modules)

× Client
  Compiled with some errors in 2.96s

× Server
  Compiled with some errors in 973.28ms

Not externalizing fs (default)
Externalizing jest-message-util (node_modules)
Externalizing @babel/code-frame (node_modules)
Not externalizing ./log (relative require)
Not externalizing ./log-apply-result (relative require)
Externalizing webpack/hot/log-apply-result (node_modules)
Not externalizing ./log (relative require)
Externalizing express (node_modules)
Not externalizing ./server (relative require)
Externalizing react (node_modules)
Not externalizing ./App (relative require)
Externalizing react-router-dom (node_modules)
Externalizing express (node_modules)
Externalizing react-dom/server (node_modules)
Not externalizing C:\Users\craig\Projects\razzle-mer-fail\build\assets.json (relative require)
Externalizing react (node_modules)
Externalizing react-router-dom (node_modules)
Not externalizing ./Home (relative require)
Not externalizing ./App.css (relative require)
Not externalizing ../node_modules/css-loader/dist/runtime/cssWithMappingToString.js (relative require)
Not externalizing ../node_modules/css-loader/dist/runtime/api.js (relative require)
Externalizing react (node_modules)
Not externalizing ./react.svg (relative require)
Not externalizing mermaid (using notNodeExternalResMatch)
Not externalizing ./Home.css (relative require)
Not externalizing ../node_modules/css-loader/dist/runtime/cssWithMappingToString.js (relative require)
Not externalizing ../node_modules/css-loader/dist/runtime/api.js (relative require)
sswp> running `node -r C:\Users\craig\Projects\razzle-mer-fail\node_modules\source-map-support\register.js C:\Users\craig\Projects\razzle-mer-fail\build\server.js -- --color --ansi`

C:\Users\craig\Projects\razzle-mer-fail\node_modules\@babel\types\lib\definitions\utils.js:130
    throw new TypeError(`Property ${key} of ${node.type} expected node to be of a type ${JSON.stringify(types)} but instead got ${JSON.stringify(val == null ? void 0 : val.type)}`);
          ^

Module build failed (from ./node_modules/razzle/config/babel-loader/razzle-babel-loader.js):
TypeError: C:\Users\craig\Projects\razzle-mer-fail\node_modules\mermaid\dist\mermaid.core.js: Property left of AssignmentExpression expected node to be of a type ["LVal"] but instead got "BooleanLiteral"

  958 | /***/ (function(module, exports) {
  959 |
> 960 | throw new Error("Module build failed (from ./node_modules/razzle/config/babel-loader/razzle-babel-loader.js):\nTypeError: C:\\Users\\craig\\Projects\\razzle-mer-fail\\node_modules\\mermaid\\dist\\mermaid.core.js: Property left of AssignmentExpression expected node to be of a type [\"LVal\"] but instead got \"BooleanLiteral\"\n    at Object.validate (C:\\Users\\craig\\Projects\\razzle-mer-fail\\node_modules\\@babel\\types\\lib\\definitions\\utils.js:130:11)\n    at validateField (C:\\Users\\craig\\Projects\\razzle-mer-fail\\node_modules\\@babel\\types\\lib\\validators\\validate.js:24:9)\n    at Object.validate (C:\\Users\\craig\\Projects\\razzle-mer-fail\\node_modules\\@babel\\types\\lib\\validators\\validate.js:17:3)\n    at NodePath._replaceWith (C:\\Users\\craig\\Projects\\razzle-mer-fail\\node_modules\\@babel\\traverse\\lib\\path\\replacement.js:147:7)\n    at NodePath.replaceWith (C:\\Users\\craig\\Projects\\razzle-mer-fail\\node_modules\\@babel\\traverse\\lib\\path\\replacement.js:129:8)\n    at replaceAndEvaluateNode (C:\\Users\\craig\\Projects\\razzle-mer-fail\\node_modules\\babel-plugin-transform-define\\lib\\index.js:37:12)\n    at processNode (C:\\Users\\craig\\Projects\\razzle-mer-fail\\node_modules\\babel-plugin-transform-define\\lib\\index.js:62:5)\n    at PluginPass.MemberExpression (C:\\Users\\craig\\Projects\\razzle-mer-fail\\node_modules\\babel-plugin-transform-define\\lib\\index.js:77:9)\n    at newFn (C:\\Users\\craig\\Projects\\razzle-mer-fail\\node_modules\\@babel\\traverse\\lib\\visitors.js:171:21)\n    at NodePath._call (C:\\Users\\craig\\Projects\\razzle-mer-fail\\node_modules\\@babel\\traverse\\lib\\path\\context.js:53:20)\n    at NodePath.call (C:\\Users\\craig\\Projects\\razzle-mer-fail\\node_modules\\@babel\\traverse\\lib\\path\\context.js:40:17)\n    at NodePath.visit (C:\\Users\\craig\\Projects\\razzle-mer-fail\\node_modules\\@babel\\traverse\\lib\\path\\context.js:90:31)\n    at TraversalContext.visitQueue (C:\\Users\\craig\\Projects\\razzle-mer-fail\\node_modules\\@babel\\traverse\\lib\\context.js:99:16)\n    at TraversalContext.visitSingle (C:\\Users\\craig\\Projects\\razzle-mer-fail\\node_modules\\@babel\\traverse\\lib\\context.js:73:19)\n    at TraversalContext.visit (C:\\Users\\craig\\Projects\\razzle-mer-fail\\node_modules\\@babel\\traverse\\lib\\context.js:127:19)\n
at Function.traverse.node (C:\\Users\\craig\\Projects\\razzle-mer-fail\\node_modules\\@babel\\traverse\\lib\\index.js:76:17)");
  961 |
  962 | /***/ }),
  963 |

    at Object.validate (C:\Users\craig\Projects\razzle-mer-fail\node_modules\@babel\types\lib\definitions\utils.js:130:11)
    at validateField (C:\Users\craig\Projects\razzle-mer-fail\node_modules\@babel\types\lib\validators\validate.js:24:9)
    at Object.validate (C:\Users\craig\Projects\razzle-mer-fail\node_modules\@babel\types\lib\validators\validate.js:17:3)
    at NodePath._replaceWith (C:\Users\craig\Projects\razzle-mer-fail\node_modules\@babel\traverse\lib\path\replacement.js:147:7)
    at NodePath.replaceWith (C:\Users\craig\Projects\razzle-mer-fail\node_modules\@babel\traverse\lib\path\replacement.js:129:8)
    at replaceAndEvaluateNode (C:\Users\craig\Projects\razzle-mer-fail\node_modules\babel-plugin-transform-define\lib\index.js:37:12)
    at processNode (C:\Users\craig\Projects\razzle-mer-fail\node_modules\babel-plugin-transform-define\lib\index.js:62:5)
    at PluginPass.MemberExpression (C:\Users\craig\Projects\razzle-mer-fail\node_modules\babel-plugin-transform-define\lib\index.js:77:9)
    at newFn (C:\Users\craig\Projects\razzle-mer-fail\node_modules\@babel\traverse\lib\visitors.js:171:21)
    at NodePath._call (C:\Users\craig\Projects\razzle-mer-fail\node_modules\@babel\traverse\lib\path\context.js:53:20)
    at NodePath.call (C:\Users\craig\Projects\razzle-mer-fail\node_modules\@babel\traverse\lib\path\context.js:40:17)
    at NodePath.visit (C:\Users\craig\Projects\razzle-mer-fail\node_modules\@babel\traverse\lib\path\context.js:90:31)
    at TraversalContext.visitQueue (C:\Users\craig\Projects\razzle-mer-fail\node_modules\@babel\traverse\lib\context.js:99:16)
    at TraversalContext.visitSingle (C:\Users\craig\Projects\razzle-mer-fail\node_modules\@babel\traverse\lib\context.js:73:19)
    at TraversalContext.visit (C:\Users\craig\Projects\razzle-mer-fail\node_modules\@babel\traverse\lib\context.js:127:19)
    at Function.traverse.node (C:\Users\craig\Projects\razzle-mer-fail\node_modules\@babel\traverse\lib\index.js:76:17)
    at Object../node_modules/mermaid/dist/mermaid.core.js (C:\Users\craig\Projects\razzle-mer-fail\build\server.js:960:7)
    at __webpack_require__ (C:\Users\craig\Projects\razzle-mer-fail\build\webpack:\webpack\bootstrap:748:1)
    at fn (C:\Users\craig\Projects\razzle-mer-fail\build\webpack:\webpack\bootstrap:59:1)
    at Module../src/Home.js (C:\Users\craig\Projects\razzle-mer-fail\build\server.js:1378:65)
    at __webpack_require__ (C:\Users\craig\Projects\razzle-mer-fail\build\webpack:\webpack\bootstrap:748:1)
    at fn (C:\Users\craig\Projects\razzle-mer-fail\build\webpack:\webpack\bootstrap:59:1)
    at Module../src/App.js (C:\Users\craig\Projects\razzle-mer-fail\build\server.js:1308:63)
    at __webpack_require__ (C:\Users\craig\Projects\razzle-mer-fail\build\webpack:\webpack\bootstrap:748:1)
    at fn (C:\Users\craig\Projects\razzle-mer-fail\build\webpack:\webpack\bootstrap:59:1)
    at Module../src/server.js (C:\Users\craig\Projects\razzle-mer-fail\build\server.js:1568:62)
```

**Comment by fivethreeo** [comment]
Using

import mermaid from 'mermaid'; ?

seems like you still use the dist import

**Comment by fivethreeo** [comment]
https://github.com/jaredpalmer/razzle/blob/07bae94b1877e7bae873e1289e95116596d3774d/packages/razzle/config/createConfigAsync.js#L474

https://webpack.js.org/configuration/devtool/

https://github.com/jaredpalmer/razzle/blob/master/packages/razzle/config/createConfigAsync.js#L289

https://babeljs.io/docs/en/options#retainlines

**Comment by fivethreeo** [comment]
Just linking some ideas on what to try out. Let me know what you find out :)

**Comment by cskeogh** [comment]
Thank you for the guidance. I wasn't able to get line numbers working. But I did solve the mermaid import problem. [Transpilation](https://razzlejs.org/docs/customization#transpilation-of-external-modules) wasn't required. I made the following change to mermaid, rebuilt mermaid, and copied the build's `dist` to `./node_modules/mermaid/dist`:

```diff
diff --git a/src/mermaid.js b/src/mermaid.js
index 07728a5d..b42407f7 100644
--- a/src/mermaid.js
+++ b/src/mermaid.js
@@ -2,7 +2,7 @@
  * Web page integration module for the mermaid framework. It uses the mermaidAPI for mermaid functionality and to render
  * the diagrams to svg code.
  */
-import decode from 'entity-decode/browser';
+import decode from 'entity-decode';
 import { log } from './logger';
 import mermaidAPI from './mermaidAPI';
 import utils from './utils';
```

I don't mind if you close the bug, or keep bug open for the line numbers.

**Comment by cskeogh** [comment]
Closing. This issue contains detail related to a second issue (added by me) that has been resolved. I'll open a new issue if occurs again.
