### ISSUE TITLE
path to src directory

### ISSUE THREAD

**Issue by rubanNg** [jaredpalmer/razzle#1653]
## ❓Question

Hello 

I start the project with the **razzle start** command.
And the command goes to the root directory by default.
But I want the **src folder** to be on a different path. How to specify where the **src folder** will be when starting the project

**Comment by fivethreeo** [comment]
Set RAZZLE_APP_PATH before start

https://github.com/jaredpalmer/razzle/blob/master/packages/razzle/config/paths.js#L11

**Comment by rubanNg** [comment]
I changed the context for the webpack and
make your way to the project
everything starts and works but an error appears in the console.



```
const fs = require('fs');
const path = require('path');
const { razzleAppPath, projects } = require('./config')

'use strict';

module.exports = {
  plugins: ['typescript'],
  modifyWebpackConfig(opts) {
    const config = opts.webpackConfig;
    config.context = __dirname;
    return config;
  },
  modifyPaths({
    webpackObject,
    options: {
      pluginOptions,
      razzleOptions,
    },
    paths,
  }) {

    return {
      dotenv: 'C:\\Projects\\razzler-ts\\.env',
      appPath: 'C:\\Projects\\razzler-ts\\energyBase\\support-f', 
      appBuild: 'C:\\Projects\\razzler-ts\\build',
      appBuildPublic: 'C:\\Projects\\razzler-ts\\build\\public',
      appAssetsManifest: 'C:\\Projects\\razzler-ts\\build\\assets.json',
      appBuildStaticExport: 'C:\\Projects\\razzler-ts\\build\\static_export.js',
      appBuildStaticExportRoutes: 'C:\\Projects\\razzler-ts\\build\\public\\static_routes.js',
      appPublic: 'C:\\Projects\\razzler-ts\\public',
      appNodeModules: 'C:\\Projects\\razzler-ts\\node_modules',
      appSrc: 'C:\\Projects\\razzler-ts\\energyBase\\support-f\\src',
      appHtml: 'C:\\Projects\\razzler-ts\\public\\index.html',
      appPackageJson: 'C:\\Projects\\razzler-ts\\package.json',
      appServerJs: 'C:\\Projects\\razzler-ts\\energyBase\\support-f\\src\\server',
      appServerIndexJs: 'C:\\Projects\\razzler-ts\\energyBase\\support-f\\src',
      appClientIndexJs: 'C:\\Projects\\razzler-ts\\energyBase\\support-f\\src\\client',
      appStaticExportJs: 'C:\\Projects\\razzler-ts\\energyBase\\support-f\\src\\static_export',
      tsTestsSetup: 'C:\\Projects\\razzler-ts\\energyBase\\support-f\\srcc\\setupTests.ts',
      jsTestsSetup: 'C:\\Projects\\razzler-ts\\energyBase\\support-f\\src\\setupTests.js',
      appBabelRc: 'C:\\Projects\\razzler-ts\\.babelrc',
      appRazzleConfig: 'C:\\Projects\\razzler-ts\\razzle.config.js',
      nodePaths: '',
      ownPath: 'C:\\Projects\\razzler-ts\\node_modules\\razzle',
      ownNodeModules: 'C:\\Projects\\razzler-ts\\node_modules\\razzle\\node_modules',
      publicUrl: undefined,
      servedPath: '/',
      appJsConfig: 'C:\\Projects\\razzler-ts\\jsconfig.json',
      appTsConfig: 'C:\\Projects\\razzler-ts\\tsconfig.json'
    }
  },
};

```


Errors

```

Error: No files matching 'C:/Projects/razzler-ts/src/**/*.{ts,tsx,js,jsx}' were found.
Error: No files matching 'C:/Projects/razzler-ts/src/**/*.{ts,tsx,js,jsx}' were found.
    at FileEnumerator.iterateFiles (C:\Projects\razzler-ts\node_modules\eslint\lib\cli-engine\file-enumerator.js:317:27)
    at iterateFiles.next (<anonymous>)
    at CLIEngine.executeOnFiles (C:\Projects\razzler-ts\node_modules\eslint\lib\cli-engine\cli-engine.js:765:48)
    at C:\Projects\razzler-ts\node_modules\razzle-plugin-typescript\node_modules\fork-ts-checker-webpack-plugin\lib\eslint-reporter\reporter\EsLintReporter.js:36:41
    at Generator.next (<anonymous>)
    at C:\Projects\razzler-ts\node_modules\razzle-plugin-typescript\node_modules\fork-ts-checker-webpack-plugin\lib\eslint-reporter\reporter\EsLintReporter.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Projects\razzler-ts\node_modules\razzle-plugin-typescript\node_modules\fork-ts-checker-webpack-plugin\lib\eslint-reporter\reporter\EsLintReporter.js:4:12)
    at getReport (C:\Projects\razzler-ts\node_modules\razzle-plugin-typescript\node_modules\fork-ts-checker-webpack-plugin\lib\eslint-reporter\reporter\EsLintReporter.js:25:66)
    at Object.<anonymous> (C:\Projects\razzler-ts\node_modules\razzle-plugin-typescript\node_modules\fork-ts-checker-webpack-plugin\lib\rpc\RpcService.js:23:38)
```

trying to find files in the root directory


**my file structure**

![image](https://user-images.githubusercontent.com/55806062/124626866-57316580-de7f-11eb-98a6-324508800a0e.png)


I expanded the webpack context so that it would be possible to import componets from the folder components

**Comment by fivethreeo** [comment]
Use tsconfig compilerOptions.paths and baseUrl

**Comment by fivethreeo** [comment]
https://github.com/jaredpalmer/razzle/blob/master/examples/with-jsconfig-paths/jsconfig.json

**Comment by rubanNg** [comment]
> Use tsconfig compilerOptions.paths and baseUrl

I did not quite understand. you can throw off the example code

**Comment by rubanNg** [comment]
I understand correctly that my config will look like this

```
{
  "compilerOptions": {
    "baseUrl": "energyBase/support-f/src",
  }
}

```

**Comment by fivethreeo** [comment]
That won't work, I think.

{
  "compilerOptions": {
    "baseUrl": "src",

    "paths": {
       "energyBase/*": "energyBase/support-f/src/*"
     }
  }
}

**Comment by fivethreeo** [comment]
https://github.com/jaredpalmer/razzle/blob/07bae94b1877e7bae873e1289e95116596d3774d/packages/razzle/config/modules.js#L32

**Comment by fivethreeo** [comment]
But the error seems to come from eslint.

**Comment by fivethreeo** [comment]
https://github.com/jaredpalmer/razzle/blob/07bae94b1877e7bae873e1289e95116596d3774d/packages/razzle/config/modules.js#L27

Maybe the idea for baseUrl you had works when you change paths.appSrc, but eslint may need some config.

**Comment by rubanNg** [comment]
a project with typescript support is apparently not very good yet. So I made a regular project and set it up as I wanted. and add the typescript to it myself

**Comment by rubanNg** [comment]
I still don't understand how to do it

**Comment by fivethreeo** [comment]
```js
'use strict';

const path = require('path');

module.exports = {
  plugins: ['typescript'],
  modifyPaths({
    webpackObject,
    options: {
      razzleOptions,
    },
    paths,
  }) {

    paths.appSrc = path.join(paths.appPath, 'energyBase/support-f/src');
    return paths;
  },
};
```


```json
{
  "compilerOptions": {
    "baseUrl": "energyBase/support-f/src",
  }
}
```

**Comment by fivethreeo** [comment]
Maybe some changes to eslint too, not sure.

**Comment by fivethreeo** [comment]
Will consider this resolved, should be doable wit minor tweaks to config.

Reopen if you feel differently 😀
