### ISSUE TITLE
In the with-typescript example imported libraries do not get transpiled correctly

### ISSUE THREAD

**Issue by iampeter** [jaredpalmer/razzle#1731]
### Current Behavior

After starting a new razzle project with the `with-typescript` example, adding these libraries to `package.json`:
```
    "react-vega": "^7.4.4",
    "vega": "^5.21.0",
    "vega-lite": "^5.0.0"
```

replacing `Home.tsx` with 
```
import React from 'react';
import logo from './react.svg';
import {VegaLite} from "react-vega";

import './Home.css';

class Home extends React.Component<{}, {}> {
  public render() {
    return (
      <div className="Home">
        <div className="Home-header">
          <img src={logo} className="Home-logo" alt="logo" />
          <h2>Welcome to Razzle</h2>
        </div>

        <VegaLite spec={{
          description: "A simple bar chart with embedded data.",
          mark: "bar",
          encoding: {
            x: { field: "a", type: "ordinal" },
            y: { field: "b", type: "quantitative" }
          }
        }} data={{ values: [
          { a: "A", b: 20 },
          { a: "B", b: 34 }
        ] }} />
      </div>
    );
  }
}

export default Home;
```

`yarn`

and 
`npm run start`

I'm getting:
```
[1] ℹ Compiling Client
[1] /home/piotr/work/ku/with-typescript/node_modules/vega-lite/build/vega-lite.js:727
[1]       deepMerge_(dest, s ?? {});
[1]                           ^
[1] 
[1] SyntaxError: Unexpected token '?'
[1]     at wrapSafe (internal/modules/cjs/loader.js:1047:16)
[1]     at Module._compile (internal/modules/cjs/loader.js:1097:27)
[1]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
[1]     at Module.load (internal/modules/cjs/loader.js:977:32)
[1]     at Function.Module._load (internal/modules/cjs/loader.js:877:14)
[1]     at Module.require (internal/modules/cjs/loader.js:1019:19)
[1]     at require (internal/modules/cjs/helpers.js:77:18)
[1]     at /home/piotr/work/ku/with-typescript/node_modules/vega-embed/build/vega-embed.js:2:108
[1]     at Object.<anonymous> (/home/piotr/work/ku/with-typescript/node_modules/vega-embed/build/vega-embed.js:5:2)
[1]     at Module._compile (internal/modules/cjs/loader.js:1133:30)
[1] sswp> !!! Script exited with code 1
```

### Expected behavior

No compilation error

### Reproducible example

https://github.com/iampeter/razzle-with-typescript

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Razzle           | 4.1.0
| Razzle Plugins   |
| Node             | 12.16.3
| Browser          |
| npm/Yarn         | 1.22.11
| Operating System | Ubuntu 20.04
| TypeScript       | 4.0.3
| React            | 17.0.1

**Comment by fivethreeo** [comment]
https://stackoverflow.com/questions/58144825/uncaught-syntaxerror-unexpected-token

**Comment by fivethreeo** [comment]
https://razzlejs.org/docs/customization#transpilation-of-external-modules

**Comment by fivethreeo** [comment]
Closing with previous doc link as solution, reopen if still a issue
