### ISSUE TITLE
npx create-razzle-app creates a broken app

### ISSUE THREAD

**Issue by silviubogan** [jaredpalmer/razzle#1751]
### Current Behavior

Just running `$ npx create-razzle-app react-mathemakid`, then `$ cd react-mathemakid` then `$ yarn start`.

The installation is fine, but when running `yarn start` and loading the page in the browser it throws me this error:

```log
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

[0m [90m 24 |[39m   [36mconst[39m context [33m=[39m {}[33m;[39m[0m
[0m [90m 25 |[39m   [36mconst[39m markup [33m=[39m renderToString([0m
[0m[31m[1m>[22m[39m[90m 26 |[39m     [33m<[39m[33mStaticRouter[39m context[33m=[39m{context} location[33m=[39m{req[33m.[39murl}[33m>[39m[0m
[0m [90m 27 |[39m       [33m<[39m[33mApp[39m [33m/[39m[33m>[39m[0m
[0m [90m 28 |[39m     [33m<[39m[33m/[39m[33mStaticRouter[39m[33m>[39m[0m
[0m [90m 29 |[39m   )[33m;[39m[0m

    at ReactDOMServerRenderer.render (/run/media/silviub/T7-Touch/Lucru/weekends/react-mathemakid/node_modules/react-dom/cjs/react-dom-server.node.development.js:4053:17)
    at ReactDOMServerRenderer.read (/run/media/silviub/T7-Touch/Lucru/weekends/react-mathemakid/node_modules/react-dom/cjs/react-dom-server.node.development.js:3690:29)
    at renderToString (/run/media/silviub/T7-Touch/Lucru/weekends/react-mathemakid/node_modules/react-dom/cjs/react-dom-server.node.development.js:4298:27)
    at renderApp (/run/media/silviub/T7-Touch/Lucru/weekends/react-mathemakid/src/server.js:26:1)
    at /run/media/silviub/T7-Touch/Lucru/weekends/react-mathemakid/build/webpack:/src/server.js:53:1
    at Layer.handle [as handle_request] (/run/media/silviub/T7-Touch/Lucru/weekends/react-mathemakid/node_modules/express/lib/router/layer.js:95:5)
    at next (/run/media/silviub/T7-Touch/Lucru/weekends/react-mathemakid/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/run/media/silviub/T7-Touch/Lucru/weekends/react-mathemakid/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/run/media/silviub/T7-Touch/Lucru/weekends/react-mathemakid/node_modules/express/lib/router/layer.js:95:5)
    at /run/media/silviub/T7-Touch/Lucru/weekends/react-mathemakid/node_modules/express/lib/router/index.js:281:22
```

If I replace

```js
import { StaticRouter } from 'react-router-dom';
```

with

```js
import { StaticRouter } from 'react-router-dom/server';
```

it throws another error:

```log
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

[0m [90m 23 |[39m [36mexport[39m [36mconst[39m renderApp [33m=[39m (req[33m,[39m res) [33m=>[39m {[0m
[0m [90m 24 |[39m   [36mconst[39m context [33m=[39m {}[33m;[39m[0m
[0m[31m[1m>[22m[39m[90m 25 |[39m   [36mconst[39m markup [33m=[39m renderToString([0m
[0m [90m 26 |[39m     [33m<[39m[33mStaticRouter[39m context[33m=[39m{context} location[33m=[39m{req[33m.[39murl}[33m>[39m[0m
[0m [90m 27 |[39m       [33m<[39m[33mApp[39m [33m/[39m[33m>[39m[0m
[0m [90m 28 |[39m     [33m<[39m[33m/[39m[33mStaticRouter[39m[33m>[39m[0m

    at ReactDOMServerRenderer.render (/run/media/silviub/T7-Touch/Lucru/weekends/react-mathemakid/node_modules/react-dom/cjs/react-dom-server.node.development.js:4053:17)
    at ReactDOMServerRenderer.read (/run/media/silviub/T7-Touch/Lucru/weekends/react-mathemakid/node_modules/react-dom/cjs/react-dom-server.node.development.js:3690:29)
    at renderToString (/run/media/silviub/T7-Touch/Lucru/weekends/react-mathemakid/node_modules/react-dom/cjs/react-dom-server.node.development.js:4298:27)
    at renderApp (/run/media/silviub/T7-Touch/Lucru/weekends/react-mathemakid/src/server.js:25:1)
    at /run/media/silviub/T7-Touch/Lucru/weekends/react-mathemakid/build/webpack:/src/server.js:52:1
    at Layer.handle [as handle_request] (/run/media/silviub/T7-Touch/Lucru/weekends/react-mathemakid/node_modules/express/lib/router/layer.js:95:5)
    at next (/run/media/silviub/T7-Touch/Lucru/weekends/react-mathemakid/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/run/media/silviub/T7-Touch/Lucru/weekends/react-mathemakid/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/run/media/silviub/T7-Touch/Lucru/weekends/react-mathemakid/node_modules/express/lib/router/layer.js:95:5)
    at /run/media/silviub/T7-Touch/Lucru/weekends/react-mathemakid/node_modules/express/lib/router/index.js:281:22
```

### Expected behavior

The app should load well in the browser, and there shouldn't be any error.

### Reproducible example

https://github.com/silviubogan/razzle-test-06.11.2021

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Razzle           | 4.2.6 |
| Razzle Plugins   |  html-webpack-plugin: 4.5.2, mini-css-extract-plugin: 0.9.0 |
| Node             | 12.22.5 |
| Browser          | Chromium 94.0.4606.81 |
| npm/Yarn         | npm: 6.14.14, yarn: 1.22.5 |
| Operating System | Manjaro Linux |
| TypeScript       | N/A |
| React            |17.0.2|

**Comment by fivethreeo** [comment]
Can confirm

 export your component from the file it's defined in, or you might have mixed up default and named imports. 

but I cant see why

**Comment by fivethreeo** [comment]
i think a newer react is installed

**Comment by fivethreeo** [comment]
`$ npx create-razzle-app react-mathemakid --example basic` works

**Comment by gustavo-zapata** [comment]
I'm getting the same error. I tried the `--example basic` and it works but I'd like to use the default version.

**Comment by gustavo-zapata** [comment]
I figured it out. Most of the issues come from `react-router-dom`. But the actual issues are the wrong implementation of this package within the `create-razzle-app` template. 

**server.js**
`import { StaticRouter } from 'react-router-dom/server'` it should be this instead of ~`import StaticRouter from 'react-router-dom'`~

**App.js**
`import { Route, Routes } from 'react-router-dom'` this instead of ~`import { Route, Switch } from 'react-router-dom'`~
`<Route exact path="/" element={<Home/>} />` and this instead of ~`<Route exact path="/" component={Home} />`~ 


razzle version: 4.2.6
react-router-dom version: 6.0.2

**Comment by RobertSandiford** [comment]
`<Route exact path="/" element={<Home/>} />`

I think react router 6 is exact by default, so you don't need `exact`

**Comment by Caesar-APAX** [comment]
@silviubogan i think you should reset package.json

such as:
```javascript
 "react-router-dom": "^5.2.0"
```

Because react-router-dom update to v6.0 version

**Comment by fivethreeo** [comment]
Fixed
