### ISSUE TITLE
with-typescript + graphql plugin: How to testing GraphQL queries

### ISSUE THREAD

**Issue by akoskm** [jaredpalmer/razzle#1793]
Using `with-typescript` and the `graphql` plugin, I'm having trouble importing my `.graphql` files in my tests.

While `.graphql` imports work fine while running the app, they seem to resolve to the filename in my tests:

```js
import { ApolloServer } from "apollo-server-express";
import typeDefs from "../../graphql/schema.graphql";
import resolvers from "../../graphql";
import GetProjects from "../../pages/account/projects.graphql";

console.log("GetProjects", GetProjects); // GetProjects projects.graphql
console.log("typeDefs", typeDefs); // typeDefs schema.graphql

describe("Project", () => {
  it("returns a list of projects", async () => {
    const server = new ApolloServer({
      typeDefs,
      resolvers,
    });

    const result = await server.executeOperation({
      query: GetProjects,
    });
    expect(result.errors).toBeUndefined();
  });
});

```

This breaks the ApolloServer initialization:

```
GraphQLError: Syntax Error: Unexpected character: ".".

       9 | describe("Project", () => {
      10 |   it("returns a list of projects", async () => {
    > 11 |     const server = new ApolloServer({
         |                    ^
      12 |       typeDefs,
      13 |       resolvers,
      14 |     });

      at syntaxError (node_modules/graphql/error/syntaxError.js:15:10)
      at readNextToken (node_modules/graphql/language/lexer.js:420:40)
      at Lexer.lookahead (node_modules/graphql/language/lexer.js:84:29)
      at Lexer.advance (node_modules/graphql/language/lexer.js:67:38)
      at Parser.expectKeyword (node_modules/graphql/language/parser.js:1444:19)
      at Parser.parseSchemaDefinition (node_modules/graphql/language/parser.js:744:10)
      at Parser.parseDefinition (node_modules/graphql/language/parser.js:165:23)
      at Parser.many (node_modules/graphql/language/parser.js:1529:26)
      at Parser.parseDocument (node_modules/graphql/language/parser.js:121:25)
      at Object.parse (node_modules/graphql/language/parser.js:32:17)
      at visitTypeSources (node_modules/@graphql-tools/merge/index.js:639:42)
      at visitTypeSources (node_modules/@graphql-tools/merge/index.js:631:17)
      at mergeGraphQLTypes (node_modules/@graphql-tools/merge/index.js:657:22)
      at Object.mergeTypeDefs (node_modules/@graphql-tools/merge/index.js:605:22)
      at makeExecutableSchema (node_modules/@graphql-tools/schema/index.js:496:38)
      at ApolloServer.constructSchema (node_modules/apollo-server-core/src/ApolloServer.ts:642:32)
      at new ApolloServerBase (node_modules/apollo-server-core/src/ApolloServer.ts:282:18)
      at new ApolloServer (node_modules/apollo-server-express/src/ApolloServer.ts:55:1)
      at Object.<anonymous> (src/graphql/Query/project.test.js:11:20)
```

**Comment by akoskm** [comment]
Any idea how to deal with `.graphql` imports in tests?
