### ISSUE TITLE
How to configure  daisy UI | TailwindCSS

### ISSUE THREAD

**Issue by Tanmay1192** [jaredpalmer/razzle#1820]
### razzle.config.js: 

const path = require('path');
const LoadableWebpackPlugin = require('@loadable/webpack-plugin');
const LoadableBabelPlugin = require('@loadable/babel-plugin');
const babelPresetRazzle = require('razzle/babel');
const argv = require("webpack-nano/argv");
const { merge } = require("webpack-merge");
const modifyBuilder = require('razzle-plugin-postcss').default

const addons = (/* string | string[] */ addonsArg) => {
  let addons = Array.isArray(addonsArg)
    ? addonsArg.filter(item => item !== true)
    : [addonsArg].filter(Boolean);

  return addons.map(addonName => require(`./config/addons/webpack.${addonName}.js`));
};

const cssConfig = {
  postcssPlugins: [
    // require('stylelint')({
    //   ignorePath: '/node_modules/**/*.css'
    // }),
    require('autoprefixer')({
      browsers: [
        '>1%',
        'last 4 versions',
        'Firefox ESR',
        'not ie < 9' // React doesn't support IE8 anyway
      ]
    })
  ]
}

const mb = modifyBuilder({ cssConfig })

module.exports = {
  plugins: [
    /**
    * Remove unused CSS on Production build using razzle-plugin-purgecss
    * Docs: https://github.com/finmavis/razzle-plugin-purgecss
    */
    {
      name: 'purgecss',
      options: {
        path: path.resolve(__dirname, 'src/**/*'),
        staticCssInDev: true,
      },
    },
    'scss',

    // require("daisyui")

  ],

  modifyWebpackConfig(opts) {
    const config = opts.webpackConfig;
    const { addons: addonsArg } = argv;
    const mergedConfig = merge(config, ...addons(addonsArg));
    return mergedConfig;
  },
  modify: (config, { dev, target }) => {
    const isDev = dev === true;
    const isWeb = target === 'web';
    const appConfig = Object.assign({}, config);

    if (isWeb) {
      const filename = path.resolve(__dirname, 'build');

      appConfig.plugins.push(
        new LoadableWebpackPlugin({
          outputAsset: false,
          writeToDisk: { filename },
        })
      );

      appConfig.output.filename = isDev
        ? 'static/js/[name].js'
        : 'static/js/[name].[chunkhash:8].js';

      appConfig.optimization = Object.assign({}, appConfig.optimization, {
        runtimeChunk: true,
        splitChunks: {
          cacheGroups: {
            commons: {
              test: /[\\/]node_modules[\\/]/,
              name: 'vendors',
            },
          },
          chunks: 'all',
          name: isDev,
        },
      });
    }
    return appConfig;
  },
  modifyWebpackOptions(opts) {
    const options = opts.options.webpackOptions;
    options.postCssOptions.plugins.unshift(require("daisyui"));
    return options;
  },
  modifyBabelOptions: () => ({
    babelrc: false,
    presets: [babelPresetRazzle],
    plugins: [LoadableBabelPlugin],
  }),

};

### Error : 
`TypeError: Cannot read properties of undefined (reading 'plugins')
    at modifyWebpackOptions (/Users/t/Documents/zen/bz-webapp/razzle.config.js:100:28)
    at /Users/t/Documents/zen/bz-webapp/node_modules/razzle/config/createConfigAsync.js:466:30
    at new Promise (<anonymous>)
    at module.exports (/Users/t/Documents/zen/bz-webapp/node_modules/razzle/config/createConfigAsync.js:76:10)
    at /Users/t/Documents/zen/bz-webapp/node_modules/razzle/scripts/build.js:94:30
    at new Promise (<anonymous>)
    at build (/Users/t/Documents/zen/bz-webapp/node_modules/razzle/scripts/build.js:90:14)
    at /Users/t/Documents/zen/bz-webapp/node_modules/razzle/scripts/build.js:49:16
Waiting for the debugger to disconnect...
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`

### Error after enabling daisy ui in plugin :
`Error: Cannot find module 'razzle-plugin-undefined' from '/Users/t/Documents/zen/bz-webapp/node_modules/razzle/config'
    at Function.resolveSync [as sync] (/Users/t/Documents/zen/bz-webapp/node_modules/razzle/node_modules/resolve/lib/sync.js:89:15)
    at loadPlugin (/Users/t/Documents/zen/bz-webapp/node_modules/razzle/config/loadPlugins.js:28:40)
    at /Users/t/Documents/zen/bz-webapp/node_modules/razzle/config/loadPlugins.js:40:12
    at Array.map (<anonymous>)
    at loadPlugins (/Users/t/Documents/zen/bz-webapp/node_modules/razzle/config/loadPlugins.js:39:18)
    at /Users/tanmayprakash/Documents/zen/bz-webapp/node_modules/razzle/config/loadRazzleConfig.js:44:9
    at new Promise (<anonymous>)
    at module.exports (/Users/t/Documents/zen/bz-webapp/node_modules/razzle/config/loadRazzleConfig.js:12:10)
    at Object.<anonymous> (/Users/t/Documents/zen/bz-webapp/node_modules/razzle/scripts/build.js:38:1)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND'
}`

@jaredpalmer @fivethreeo @rhodee

**Comment by Tanmay1192** [comment]
Package.json: 

 "autoprefixer": "^10.4.2",
"daisyui": "^1.25.4",
 "tailwindcss": "^3.0.18",
"postcss": "^8.4.6",

**Comment by fivethreeo** [comment]
Dasiui is not a razzle plugin. modifyBabelOptions and modify are no longer hooks in razzle.

**Comment by fivethreeo** [comment]
Is this latest razzle?
