### ISSUE TITLE
Server.js not working without node_modules folder after production build

### ISSUE THREAD

**Issue by eakarpov** [jaredpalmer/razzle#1860]
### Current Behavior

1. build razzle project with npm run build
2. locally everything is ok
3. on the server there is an error

internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module 'express'
Require stack:
- /var/www/allslavic/server.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.860 (/var/www/allslavic/server.js:1:64461)
    at t (/var/www/allslavic/server.js:1:66373)
    at /var/www/allslavic/server.js:1:66865
    at /var/www/allslavic/server.js:1:67024
    at Object.<anonymous> (/var/www/allslavic/server.js:1:67045)
    at Module._compile (internal/modules/cjs/loader.js:1085:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/var/www/allslavic/server.js' ]
}

Why dependencies have not been loaded in the bundle? Who to fix it?

### Expected behavior

Production bundle works without node-modules folder

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Razzle           | 4.2.16
| Razzle Plugins   |
| Node             | 4.16.0
| Browser          | Chrome 100
| npm/Yarn         | npm 6.14.11
| Operating System | Ubuntu Focal
| TypeScript       | 4.0.3
| React            | 18.1.0

**Comment by fivethreeo** [comment]
Set buildType to iso-serverless

https://razzlejs.org/docs/customization#options

https://github.com/jaredpalmer/razzle/discussions/1790

**Comment by eakarpov** [comment]
Thanks! It worked as expected
