### ISSUE TITLE
Jest weird behaviour

### ISSUE THREAD

**Issue by FabioAntunes** [jaredpalmer/razzle#343]
When using a barrel `index.js` to import some functions I'm getting some weird error with jest.

Steps to reproduce on a new project with razzle,  create a new folder, let's call it functions,  `src/functions`

Create a file inside `src/functions/index.js`

```
export * from './functions'
```

Create another file, `src/functions/functions.js`
```
export function foo() {
  return `foo`
}

export function bar() {
  return `bar`
}
```

Import those functions on your App.js:
```diff
import React from 'react';
import Route from 'react-router-dom/Route';
import Switch from 'react-router-dom/Switch';
import Home from './Home';
+ import { foo, bar } from './functions'
import './App.css';


const App = () =>
+  <div>
    <Switch>
      <Route exact path="/" component={Home} />
    </Switch>;

+    { foo() }
+    { bar() }
+  </div>

export default App;
```

Output
```
PATH/src/functions/index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){'use strict';import _Object$defineProperty from 'babel-runtime/core-js/object/define-property';import _Object$keys from 'babel-runtime/core-js/object/keys';exports.__esModule = true;var _functions = require('./functions');_Object$keys(_functions).forEach(function (key) {if (key === "default" || key === "__esModule") return;_Object$defineProperty(exports, key, { enumerable: true, get: function get() {return _functions[key];} });});
                                                                                                          ^^^^^^
    SyntaxError: Unexpected token import

      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/ScriptTransformer.js:289:17)
      at Object.<anonymous> (src/App.js:5:18)
      at Object.<anonymous> (src/App.test.js:1:180)
```

Repeat the same with a `create-react-app` everything works fine.

**Comment by FabioAntunes** [comment]
Might be related to this? https://github.com/babel/babel/issues/2877

**Comment by FabioAntunes** [comment]
Ok so I managed to fix it by changing the `babel-razzle-preset`

```diff
// Add support for async/await
- require.resolve('babel-plugin-transform-runtime'),
+ [require.resolve('babel-plugin-transform-runtime'), {polyfill: false} ],
```

I'm guessing that we only want to apply this config to the **test** ENV

**Comment by jaredpalmer** [comment]
Move to #345
