### ISSUE TITLE
SyntaxError: Unexpected token ... in razzle.config.js

### ISSUE THREAD

**Issue by mbrochh** [jaredpalmer/razzle#402]
I cloned the repo and tried the with-react-loadable example but I'm getting this error when I run `yarn start`:

```
 ERROR  Invalid razzle.config.js file.

/Users/martin/Projects/theartling/testing-ground/razzle/repo/razzle/examples/with-react-loadable/razzle.config.js:7
        ...config,
        ^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/martin/Projects/theartling/testing-ground/razzle/repo/razzle/examples/with-react-loadable/node_modules/razzle/scripts/start.js:29:14)
error Command failed with exit code 1.
```

**Comment by mbrochh** [comment]
Hmm strange. I did `yarn add babel-plugin-transform-object-rest-spread` and now it works. I don't understand why, because this dependency is clearly listed in dev-depencendies. :(
