### ISSUE TITLE
Basic example not working with React 16.2+

### ISSUE THREAD

**Issue by kireerik** [jaredpalmer/razzle#419]
Windows, Node.js 9.2, Yarn 1.3.2

Console log:
```shell
yarn start
yarn run v1.3.2
$ razzle start
 WAIT  Compiling...

 ERROR  Failed to compile CLIENT with 18 errors

./src/client.js
Module not found: Can't resolve 'react' in '...\basic\src'

 ERROR  Failed to compile CLIENT with 18 errors

./node_modules/react-error-overlay/lib/index.js
Module not found: Can't resolve 'react' in '...\basic\node_modules\react-error-overlay\lib'

 ERROR  Failed to compile CLIENT with 18 errors

./src/App.js
Module not found: Can't resolve 'react' in '...\basic\src'

 ERROR  Failed to compile CLIENT with 18 errors

./node_modules/react-error-overlay/lib/containers/CompileErrorContainer.js
Module not found: Can't resolve 'react' in '...\basic\node_modules\react-error-overlay\lib\containers'

 ERROR  Failed to compile CLIENT with 18 errors

./node_modules/react-error-overlay/lib/containers/RuntimeErrorContainer.js
Module not found: Can't resolve 'react' in '...\basic\node_modules\react-error-overlay\lib\containers'

 ERROR  Failed to compile CLIENT with 18 errors

./node_modules/react-error-overlay/lib/containers/RuntimeError.js
Module not found: Can't resolve 'react' in '...\basic\node_modules\react-error-overlay\lib\containers'

 ERROR  Failed to compile CLIENT with 18 errors

./node_modules/react-error-overlay/lib/components/Footer.js
Module not found: Can't resolve 'react' in '...\basic\node_modules\react-error-overlay\lib\components'

 ERROR  Failed to compile CLIENT with 18 errors

./node_modules/react-error-overlay/lib/components/ErrorOverlay.js
Module not found: Can't resolve 'react' in '...\basic\node_modules\react-error-overlay\lib\components'

 ERROR  Failed to compile CLIENT with 18 errors

./node_modules/react-error-overlay/lib/components/Header.js
Module not found: Can't resolve 'react' in '...\basic\node_modules\react-error-overlay\lib\components'

 ERROR  Failed to compile CLIENT with 18 errors

./node_modules/react-error-overlay/lib/components/CodeBlock.js
Module not found: Can't resolve 'react' in '...\basic\node_modules\react-error-overlay\lib\components'

 ERROR  Failed to compile CLIENT with 18 errors

./node_modules/react-error-overlay/lib/components/CloseButton.js
Module not found: Can't resolve 'react' in '...\basic\node_modules\react-error-overlay\lib\components'

 ERROR  Failed to compile CLIENT with 18 errors

./node_modules/react-error-overlay/lib/components/NavigationBar.js
Module not found: Can't resolve 'react' in '...\basic\node_modules\react-error-overlay\lib\components'

 ERROR  Failed to compile CLIENT with 18 errors

./src/client.js
Module not found: Can't resolve 'react-dom' in '...\basic\src'

 ERROR  Failed to compile CLIENT with 18 errors

./node_modules/react-error-overlay/lib/index.js
Module not found: Can't resolve 'react-dom' in '...\basic\node_modules\react-error-overlay\lib'

 ERROR  Failed to compile CLIENT with 18 errors

./node_modules/react-error-overlay/lib/containers/StackTrace.js
Module not found: Can't resolve 'react' in '...\basic\node_modules\react-error-overlay\lib\containers'

 ERROR  Failed to compile CLIENT with 18 errors

./node_modules/react-error-overlay/lib/containers/StackFrame.js
Module not found: Can't resolve 'react' in '...\basic\node_modules\react-error-overlay\lib\containers'

 ERROR  Failed to compile CLIENT with 18 errors

./node_modules/react-error-overlay/lib/components/Collapsible.js
Module not found: Can't resolve 'react' in '...\basic\node_modules\react-error-overlay\lib\components'

 ERROR  Failed to compile CLIENT with 18 errors

./node_modules/react-error-overlay/lib/containers/StackFrameCodeBlock.js
Module not found: Can't resolve 'react' in '...\basic\node_modules\react-error-overlay\lib\containers'
```

**Comment by kireerik** [comment]
I get the following errors if I am using Razzle version `0.7.6-rc2`:

```powershell
DONE  Compiled successfully

Your application is running at http://127.0.0.1:80

module.js:544
    throw err;
    ^

Error: Cannot find module 'react'
    at Function.Module._resolveFilename (module.js:542:15)
    at Function.Module._load (module.js:472:25)
    at Module.require (module.js:585:17)
    at require (internal/module.js:11:18)
    at Object.react (...\build\server.js:822:18)
    at __webpack_require__ (...\build\server.js:630:30)
    at fn (...\build\server.js:48:20)
    at eval (webpack-internal:///./src/server.js:8:64)
    at Object../src/server.js (...\build\server.js:729:1)
    at __webpack_require__ (...\build\server.js:630:30)
 ERROR  Failed to compile CLIENT with 1 errors

./src/client.js
Module not found: Can't resolve 'react-dom' in '...\src'
```

Also the `node_modules/react` and `node_modules/react-dom` folders are missing some files.

**Comment by kireerik** [comment]
Sorry for reporting this. This is potentially an issue with @yarnpkg as the installation or the upgrade process works with [npm](https://www.npmjs.com/).

Note: I will close this issue once the [original issue](https://github.com/yarnpkg/yarn/issues/5070) is resolved.
