### ISSUE TITLE
react-storybook

### ISSUE THREAD

**Issue by romainquellec** [jaredpalmer/razzle#425]
Hello ! 

By any chance, do you have an example with react-storybook ? Shoundn't be difficult to add but for some reason, I failed to do it.

Thanks (for this awesome project ;)).

**Comment by jariz** [comment]
What difficulties were you having?

**Comment by mkozhukharenko** [comment]
is it possible to get a webpack config? It should be passed to storybook. Like [rewired](https://github.com/timarney/react-app-rewired#4-provide-rewired-webpack-config-for-3rd-party-tools) do

**Comment by stereobooster** [comment]
> is it possible to get a webpack config? It should be passed to storybook. 

Need the same for styleguidist.

**Comment by romainquellec** [comment]
Well, it was working for some time without custom config. Webpack used the default webpack setup based on "Create React App" and it was fine. Now, its not.

I guess the webpack config changed in React App. Can we used the webpack config from razzle ?
I'm looking the issue right now.

**Comment by romainquellec** [comment]
And today, I can't reproduce the error. It's something related to storybook and webpack config from Create React App.
Still, an example with a custom webpack can be useful. You can look at [This example](https://github.com/romainquellec/cuistot-renew) for basic use.

**Comment by romainquellec** [comment]
I cant reproduce it. I'm closing this.

**Comment by bmcmurray** [comment]
This appears to still be an issue.

To reproduce:

- Set up a new razzle app using `create-razzle-app` per the instructions
- Add storybook following the storybook-react instructions <https://storybook.js.org/basics/guide-react/>
- Run `npm run storybook`

Storybook will error out with output similar to this:

```
$ npm run storybook

> my-razzle-app@2.0.0-alpha.8 storybook ~/test
> start-storybook -p 9001 -c .storybook

info @storybook/react v3.4.8
info
exec: fatal: not a git repository (or any of the parent directories): .git

exec: fatal: not a git repository (or any of the parent directories): .git

info => Using default webpack setup based on "Create React App".
~/test/node_modules/webpack/lib/DefinePlugin.js:73
		compiler.hooks.compilation.tap(
		               ^

TypeError: Cannot read property 'compilation' of undefined
    at DefinePlugin.apply (~/test/node_modules/webpack/lib/DefinePlugin.js:73:18)
    at Compiler.apply (~/test/node_modules/@storybook/core/node_modules/tapable/lib/Tapable.js:375:16)
    at webpack (~/test/node_modules/@storybook/core/node_modules/webpack/lib/webpack.js:33:19)
    at exports.default (~/test/node_modules/@storybook/core/dist/server/middleware.js:29:40)
    at buildDev (/Users/mcmurray/Documents/Work/nextgen/test/node_modules/@storybook/core/dist/server/build-dev.js:163:36)
    at Object.<anonymous> (~/test/node_modules/@storybook/react/dist/server/index.js:23:22)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (~/test/node_modules/@storybook/react/bin/index.js:3:1)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! my-razzle-app@2.0.0-alpha.8 storybook: `start-storybook -p 9001 -c .storybook`
npm ERR! Exit status 1
```

**Comment by nileshgulia1** [comment]
I got the same error with styleguidist. Does someone have an idea on how to point razzle's custom webpack configs to styleguidist?
-cc @stereobooster  Did you find anything related?
