### ISSUE TITLE
yarn run fails due to port 3001 already in use

### ISSUE THREAD

**Issue by frebro** [jaredpalmer/razzle#454]
Hey! When I did `create-dazzle-app` and then `yarn start` I got the following error:
```
yarn run v1.3.2
$ razzle start
 WAIT  Compiling...

events.js:137
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::3001
    at Object._errnoException (util.js:1003:13)
    at _exceptionWithHostPort (util.js:1024:20)
    at Server.setupListenHandle [as _listen2] (net.js:1366:14)
    at listenInCluster (net.js:1407:12)
    at Server.listen (net.js:1495:7)
    at Server.listen (/node_modules/webpack-dev-server/lib/Server.js:479:47)
    at Object.<anonymous> (/node_modules/razzle/scripts/start.js:80:17)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Function.Module.runMain (module.js:701:10)
    at startup (bootstrap_node.js:193:16)
    at bootstrap_node.js:617:3
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
I had another app running at port 3001 so I guess the fault lies with me, but the error handling could be better. Here's the relevant code:
https://github.com/jaredpalmer/razzle/blob/84209ea95a28abae28e44b03f57c9beaebcb904d/packages/razzle/scripts/start.js#L79-L92

**Comment by shelldandy** [comment]
@frebro right there is the answer, you can provide a `PORT` when starting up

`PORT=5000 npm start`

what could be done is what create-react-app does on its react-dev-utils

https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/scripts/start.js#L71-L72

Use the `choosePort` function

**Comment by frebro** [comment]
My issue was with the error handling when a port is not provided. The `choosePort` function used in create-react-app should circumvent that problem like :raised_hands:
