### ISSUE TITLE
Error: Cannot find module (2.0.0-alpha.7)

### ISSUE THREAD

**Issue by ferdinandsalis** [jaredpalmer/razzle#565]
node: `8.9.1`
razzle: `2.0.0-alpha.7`

I am getting the following error.
```
Error: Cannot find module "/Users/ferdinand/Code/louise/packages/louise-insure/build/assets.json"
      at webpackMissingModule (/Users/ferdinand/Code/louise/packages/louise-insure/build/server.js:56790:80)
      at buildHtmlString (/Users/ferdinand/Code/louise/packages/louise-insure/build/server.js:56790:226)
      at _callee3$ (/Users/ferdinand/Code/louise/packages/louise-insure/build/server.js:56654:24)
      at tryCatch (/Users/ferdinand/Code/louise/packages/louise-insure/node_modules/regenerator-runtime/runtime.js:62:40)
      at Generator.invoke [as _invoke] (/Users/ferdinand/Code/louise/packages/louise-insure/node_modules/regenerator-runtime/runtime.js:296:22)
      at Generator.prototype.(anonymous function) [as next] (/Users/ferdinand/Code/louise/packages/louise-insure/node_modules/regenerator-runtime/runtime.js:114:21)
      at step (/Users/ferdinand/Code/louise/packages/louise-insure/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
      at /Users/ferdinand/Code/louise/packages/louise-insure/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
      at <anonymous>
      at process._tickDomainCallback (internal/process/next_tick.js:228:7)
```
This is where I am using the assets manifest.
```js
const buildHtmlString = ({
  initialData,
  initialMachineState,
  html,
  css,
  ids
}) => {
  const assets = require(process.env.RAZZLE_ASSETS_MANIFEST)

  return `
    <!doctype html>
      <html>
      <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta charset="utf-8" />
        <title>Louise</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="https://fonts.googleapis.com/css?family=Alegreya+Sans:400,700|Alegreya:400,700" rel="stylesheet"> 
        <style>${css}</style>
        ${
          process.env.NODE_ENV === 'production'
            ? `<script src="${assets.client.js}" defer></script>`
            : `<script src="${assets.client.js}" defer crossorigin></script>`
        }
      </head>
      <body>
        <div id="root">${html}</div>
        <div id="portal"></div>
        <script>
          window.__CRITICAL_CSS_IDS__ = ${JSON.stringify(ids)};
          window.__INITAL_DATA__ = ${JSON.stringify(initialData)};
          window.__INITIAL_MACHINE_STATE__ = ${JSON.stringify(
            initialMachineState
          )};
        </script>
        <script id="stripe-js" src="https://js.stripe.com/v3/" async></script>
      </body>
    </html>
`
}
```
Taking a look at the file renders the following result.
```
$ cat /Users/ferdinand/Code/louise/packages/louise-insure/build/assets.json
{"client":{"js":"http://localhost:3001/static/js/bundle.js"}}
```
I am using lerna and yarn workspaces and `razzle` is not being hoisted by adding it to `nohoist`
```json
"nohoist": [
  "**/razzle",
  "**/razzle/**"
]
```
I hope I have all the relevant bits covered. Any ideas. Thanks!

**Comment by juicycleff** [comment]
Same issue happening to me

**Comment by jaredpalmer** [comment]
What does nohoist do?

**Comment by ferdinandsalis** [comment]
`nohoist` does not hoist a dependency to the root `node_modules` folder. However I have stopped using yarn workspaces and gone back to using lerna with npm. The issue is still a problem.

**Comment by lfantone** [comment]
I have the same issue but I'm not using `yarn workspaces` nor `lerna`:
```
→ yarn start
yarn run v1.5.1
$ razzle start
 WAIT  Compiling...

Hooking build for env production (web)
Hooking build for env production (node)
✔ success server compiled in 4s 496ms

Compiling

● client █████████████████████████ building modules (69%) 909/918 modules 9 active
  node_modules/apollo-cache/lib/cache.js

● server

webpack-internal:///./src/server.js:20
var assets = __webpack_require__(!(function webpackMissingModule() { var e = new Error("Cannot find module \"/Users/lfantone/Workspace/react-flight-status-cms/build/assets.json\""); e.code = 'MODULE_NOT_FOUND'; throw e; }()));
                                                      ^

Error: Cannot find module "/Workspace/razzle-app/build/assets.json"
    at webpackMissingModule (webpack-internal:///./src/server.js:20:78)
    at eval (webpack-internal:///./src/server.js:20:222)
✔ success client compiled in 6s 370ms
✔ success server compiled in 125ms
✅  Server-side HMR Enabled!
🚀 started
```
