### ISSUE TITLE
Error in razzle.config.js with Typescript

### ISSUE THREAD

**Issue by romainquellec** [jaredpalmer/razzle#622]
Hello.

With the default config with "with-typescript", I have this :

``ReferenceError:` include is not defined
    at Object.modify (C:\Users\Romain\Documents\GitHub\cuistot\frontend\razzle.config.js:26:7)
    at main (C:\Users\Romain\Documents\GitHub\cuistot\frontend\node_modules\razzle\scripts\start.js:52:27)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:118:7)``

I changed the order, in razzle.config.js.

```
// Locate eslint-loader and remove it (we're using tslint instead)
    config.module.rules = config.module.rules.filter(
      rule =>
        !(
          Array.isArray(rule.use) &&
          rule.use.length > 0 &&
          rule.use[0].options &&
          'useEslintrc' in rule.use[0].options
        )
    );

    // Safely locate Babel-Loader in Razzle's webpack internals
    const babelLoader = config.module.rules.findIndex(
      rule => rule.use[1].options && rule.use[1].options.babelrc
    );
```

(This block two blocks up)
I'm surprise nobody saw this error. Am I the only one to used typescript ? :D
Can somebody confirm, then I will do a PR.

**Comment by romainquellec** [comment]
Nevermind, already a PR #602

**Comment by romainquellec** [comment]
Fixed by Typescript plugin
