### ISSUE TITLE
The "path" argument must be of type string. Received type undefined

### ISSUE THREAD

**Issue by MarkLyck** [jaredpalmer/razzle#687]
When running `yarn start`

I get the following error:

```
/.../build/server.js:960
throw new Error("Module build failed (from ./node_modules/thread-loader/dist/cjs.js):\nThread Loader (Worker 9)\n/.../src/server.js: The \"path\" argument must be of type string. R
eceived type undefined\n\n    at assertPath (path.js:39:11)\n    at extname (path.js:1375:5)\n    at applyPlugin (/.../node_modules/babel-plugin-inline-react-svg/lib/index.js:65:27
)\n    at PluginPass.CallExpression (.../node_modules/babel-plugin-inline-react-svg/lib/index.js:151:13)\n    at newFn (/.../node_modules/babel-traverse/l
ib/visitors.js:276:21)\n    at NodePath._call (/.../node_modules/babel-traverse/lib/path/context.js:76:18)\n    at NodePath.call (/.../node_modules/babel-t
raverse/lib/path/context.js:48:17)\n    at NodePath.visit (/.../node_modules/babel-traverse/lib/path/context.js:105:12)\n    at

Error: Module build failed (from ./node_modules/thread-loader/dist/cjs.js):
Thread Loader (Worker 9)
/.../src/server.js: The "path" argument must be of type string. Received type undefined

    at assertPath (path.js:39:11)
    at extname (path.js:1375:5)
    at applyPlugin (/.../node_modules/babel-plugin-inline-react-svg/lib/index.js:65:27)
    at PluginPass.CallExpression (/.../node_modules/babel-plugin-inline-react-svg/lib/index.js:151:13)
    at newFn (/.../node_modules/babel-traverse/lib/visitors.js:276:21)
    at NodePath._call (/.../node_modules/babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (/.../node_modules/babel-traverse/lib/path/context.js:48:17)
    at NodePath.visit (/.../node_modules/babel-traverse/lib/path/context.js:105:12)
    at TraversalContext.visitQueue (/.../node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitSingle (/.../node_modules/babel-traverse/lib/context.js:108:19)
    at Object../src/server.js (/.../build/server.js:960:7)
    at __webpack_require__ (/.../build/server.js:681:30)
    at fn (/.../build/server.js:58:20)
    at Module../src/index.js (/.../build/server.js:920:65)
    at __webpack_require__ (.../build/server.js:681:30)
    at fn (/.../build/server.js:58:20)
    at Object.0 (/.../build/server.js:972:18)
    at __webpack_require__ (/.../build/server.js:681:30)
    at module.exports../node_modules/webpack/hot/log-apply-result.js.module.exports (/.../build/server.js:748:37)
    at Object.<anonymous> (/.../build/server.js:751:10)
```

This started happening after I upgraded to the latest 2.2.0 version of fs-razzle.

The error goes away when I remove `babel-plugin-inline-react-svg` plugin, so there's some incompatibility issue, possibly with the breaking change for babel-loader / thread-loader?

Broken with both versions `babel-plugin-inline-react-svg` 0.5.2 & 0.5.3

**Comment by kopax** [comment]
This helped me, we downgraded from 0.5.1. I don't know what is your module.

**Comment by ljharb** [comment]
Looks like @kopax filed this as https://github.com/airbnb/babel-plugin-inline-react-svg/issues/47 - thanks! I'll look into it.

**Comment by ljharb** [comment]
v0.5.4 should fix this issue.

**Comment by kopax** [comment]
I've tested v0.5.4 and it fixed my issue.

**Comment by SaraVieira** [comment]
@jaredpalmer I think you can close this 🎉
