### ISSUE TITLE
Monorepo and Babel

### ISSUE THREAD

**Issue by rjerue** [jaredpalmer/razzle#767]
Hello,

I've got a question on how to configure babel for a monorepo setup strung together with Lerna.

I've got two repos that I want to get sync'd up. The first is a component library that is built with react-native / react-native web. In my example, I'll call it `common`.

The second is just a website built with react.js that imports stuff from the `common` dir. It was generated with Razzle.

I like the CRA-like experience with Razzle, and would like to use it as opposed to the nasty and mysterious webpack config that I had on a previous project.

I'm getting what looks like babel isn't traspiling the things in `common` to something more node friendly. This is what I've given a try.

```
'use-strict';

const path = require('path');
const fs = require('fs');

const appDirectory = fs.realpathSync(process.cwd());
const resolveApp = relativePath => path.resolve(appDirectory, relativePath);

module.exports = {
  modify: (config, { target, dev }, webpack) => {
    // do something to config
    config.resolve.modules.push(resolveApp('../common/node_modules'))
    config.resolveLoader.modules.push(resolveApp('../common/node_modules'))
    config.module.rules[2].include.push(resolveApp('../common')),
    config.module.rules[2].exclude = [resolveApp('../common/node_modules')]
    config.module.rules[2].use[0].options.presets = ['react', 'stage-0', 'env']
    config.module.rules[2].use[0].options.plugins = [
      "babel-plugin-transform-export-extensions",
      "babel-plugin-transform-es2015-modules-commonjs"
    ]
    return config;
  },
};
```

error that I am getting -- it looks like the carrots are over 'react'. I think it's that node doesn't like the import keyword because it's not turning into modules.

```
(function (exports, require, module, __filename, __dirname) { import React, { Component } from 'react';
                                                                     ^^^^^

SyntaxError: Unexpected identifier
    at new Script (vm.js:74:7)
    at createScript (vm.js:246:10)
    at Object.runInThisContext (vm.js:298:10)
    at Module._compile (internal/modules/cjs/loader.js:657:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
```

I realize that putting the babel presets directly in webpack is odd, this is because I make a .babelrc file like such

```
{
  "presets": ["razzle/babel", "react", "stage-0", "env"],
  "plugins": [
    "babel-plugin-transform-export-extensions",
    "babel-plugin-transform-es2015-modules-commonjs"
  ]
}
```

That it freaks out at the JSX stating that there is an unexpected token.

What changes do I need to make to the babel config or `razzle.config.js`?

Thanks!

**Comment by jordmccord** [comment]
@rjerue did you find a solution to this problem by any chance?

**Comment by andycmaj** [comment]
@jordmccord @rjerue 
i have had some good luck re-implementing something like this: https://github.com/martpie/next-transpile-modules/blob/master/src/next-transpile-modules.js

ends up looking like:

```
'use strict';
const path = require('path');

const PATH_DELIMITER = '[\\\\/]'; // match 2 antislashes or one slash

/**
 * On Windows, the Regex won't match as Webpack tries to resolve the
 * paths of the modules. So we need to check for \\ and /
 */
const safePath = module => module.split(/[\\/]/g).join(PATH_DELIMITER);

const generateIncludes = modules => {
  return [
    new RegExp(`(${modules.map(safePath).join('|')})$`),
    new RegExp(
      `(${modules.map(safePath).join('|')})${PATH_DELIMITER}(?!.*node_modules)`
    ),
  ];
};

module.exports = {
  options: {
    buildType: 'serverless',
    useReactRefresh: true,
  },
  modifyWebpackOptions: ({ options: { webpackOptions } }) => {
    const includes = generateIncludes(['shared']);
    const excludes = generateExcludes(['shared']);
    webpackOptions.babelRule = {
      ...webpackOptions.babelRule,
      exclude: excludes,
      include: [...webpackOptions.babelRule.include, ...includes],
    };

    return webpackOptions;
  },
  modifyWebpackConfig({
    env: {
      target, // the target 'node' or 'web'
      dev, // is this a development build? true or false
    },
    webpackConfig, // the created webpack config
  }) {
    const config = Object.assign({}, webpackConfig);

    const isLambdaBuild = !!process.env.LAMBDA;
    return target === 'node'
      ? {
          ...config,
          output: isLambdaBuild
            ? {
                ...config.output,
                libraryTarget: 'commonjs',
              }
            : config.output,
          optimization: {
            minimize: false,
          },
        }
      : config;
  },
};


```
