### ISSUE TITLE
convert create-react-app to razzle

### ISSUE THREAD

**Issue by egaleme** [jaredpalmer/razzle#856]

**Comment by egaleme** [comment]
can i convert my create-react-app to a razzle app

**Comment by Evanion** [comment]
well the bulk of the application should just be copy paste ...
You might have to refactor some stuff like state manager (redux, mobx) to initiate differently in server and client. But the main internals should be just copy/paste.

If you are using LocalStorage to handle auth tokens, I would recommend refactoring it to use cookies as LocalStorage doesn't work with SSR.

**Comment by jaredpalmer** [comment]
I should write a post on this. It’s fairly straight forward. although we do need to catch up to some of the newest CRA features like .gql and compiling node_modules

**Comment by Evanion** [comment]
@jaredpalmer I have a PR (#841) in relation to `.gql` files open.

**Comment by egaleme** [comment]
Thanks for your reply. i have serious headache using nextjs. Most of the libraries i used in my create react app  just kept throwing errors with nextjs.

**Comment by egaleme** [comment]
hi, i'm having issues of syntax error trying to use this package react-images-upload with razzlejs.

**Comment by egaleme** [comment]
please i'm having this error when using react-images-upload with razzle. what do i do?

C:\Projects\razzlejs-projects\test-app\node_modules\react-images-upload\UploadIcon.svg:1
(function (exports, require, module, __filename, __dirname) { <svg enable-background="new 0 0 64 64" height="64px" id="Layer_1" version="1.1" viewBox="0 0 64 64" width="64px" xml:space="preserve" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"><g><path d="   M10,41.3v12c0,1.1,0.9,2,2,2h40c1.1,0,2-0.9,2-2v-12H10z" fill="none" stroke="#4D4D4D" stroke-linecap="round" stroke-linejoin="round" stroke-miterlimit="10" stroke-width="2"/><path d="   M42.6,19.4c3.8,7.3,7.6,14.7,11.4,22c-14.7,0-29.3,0-44,0c3.8-7.3,7.6-14.7,11.4-22" fill="none" stroke="#4D4D4D" stroke-linecap="round" stroke-linejoin="round" stroke-miterlimit="10" stroke-width="2"/><g><line fill="none" stroke="#4D4D4D" stroke-linecap="round" stroke-linejoin="round" stroke-miterlimit="10" stroke-width="2" x1="32" x2="32" y1="8.7" y2="28.2"/><line fill="none" stroke="#4D4D4D" stroke-linecap="round" stroke-linejoin="round" stroke-miterlimit

SyntaxError: Unexpected token <
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:657:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)

**Comment by cseas** [comment]
@jaredpalmer Any update on the blog post for this? :)

**Comment by ghost** [comment]
@jaredpalmer can you please write a post about migrating CRA to Razzle?

**Comment by ahmed-jawad828** [comment]
> I should write a post on this. It’s fairly straight forward. although we do need to catch up to some of the newest CRA features like .gql and compiling node_modules

Sir, any update about the migration guide?

**Comment by kirtirajsinh** [comment]
Can I just add razzle in my create-react-app repo? I don't wanna migrate or change something. If yes Can you suggest some repo which has already done it.
