### ISSUE TITLE
ReferenceError: window is not defined

### ISSUE THREAD

**Issue by Abhisiet50** [jaredpalmer/razzle#913]
I'm using a fine-uploader  packages  thats depends `window` and `document` . 

What is the suggested way to use libraries that uses `window` and  `document` , can I conditionally import it depending on if we're on the server or the client?

**Comment by HamidTanhaei** [comment]
```
if(typeof(window) === 'undefined') {
    //server
} esle {
    //browser
}
```

**Comment by Abhisiet50** [comment]
i use this but not work ,
ReferenceError: window is not defined
    at Object.window (c:\rentmantra_ssr\node_modules\fine-uploader\fine-uploader\?:1:32)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (c:\rentmantra_ssr\node_modules\fine-uploader\lib\core\index.js:3:18)
    at Module._compile (module.js:652:30)

**Comment by adamthewan** [comment]
Why was this closed? What is the solution?

**Comment by klarstrup** [comment]
It's a package level problem, wholly unrelated to Razzle.

That said, you may be able to dodge the problem by using a dynamic import only on the client

**Comment by zaykhere** [comment]
@klarstrup I know I'm pretty late to this but how do I use dynamic import?
