### ISSUE TITLE
Can't load scss from third party library

### ISSUE THREAD

**Issue by IanBarbour** [jaredpalmer/razzle#935]
```(function (exports, require, module, __filename, __dirname) { .zk-hover {

                                                              

SyntaxError: Unexpected token .

    at new Script (vm.js:51:7)

    at createScript (vm.js:138:10)

    at Object.runInThisContext (vm.js:199:10)

    at Module._compile (module.js:626:28)

    at Object.Module._extensions..js (module.js:673:10)

    at Module.load (module.js:575:32)

    at tryModuleLoad (module.js:515:12)

    at Function.Module._load (module.js:507:3)

    at Module.require (module.js:606:17)

    at require (internal/module.js:11:18)

No type errors found

No lint errors found

Version: typescript 3.3.3333, tslint 5.12.1

Time: 7288ms

```

```'use strict';



const autoprefixer = require('autoprefixer');

const MiniCssExtractPlugin = require('mini-css-extract-plugin');

const PostCssFlexBugFixes = require('postcss-flexbugs-fixes');

const paths = require('razzle/config/paths');



const defaultOptions = {

  postcss: {

    dev: {

      sourceMap: true,

      ident: 'postcss',

    },

    prod: {

      sourceMap: false,

      ident: 'postcss',

    },

    plugins: [

      PostCssFlexBugFixes,

      autoprefixer({

        browsers: ['>1%', 'last 4 versions', 'Firefox ESR', 'not ie < 9'],

        flexbox: 'no-2009',

      }),

    ],

  },

  sass: {

    dev: {

      sourceMap: true,

      includePaths: [paths.appNodeModules],

    },

    prod: {

      sourceMap: false,

      includePaths: [paths.appNodeModules],

    }

  },

  css: {

    dev: {

      sourceMap: true,

      importLoaders: 1,

      modules: false,

    },

    prod: {

      sourceMap: false,

      importLoaders: 1,

      modules: false,

      minimize: true,

    },

  },

  style: {},

  resolveUrl: {

    dev: {},

    prod: {},

  },

};



module.exports = (

  defaultConfig,

  { target, dev },

  webpack,

  userOptions = {}

) => {

  const isServer = target !== 'web';

  const constantEnv = dev ? 'dev' : 'prod';



  const config = Object.assign({}, defaultConfig);



  const options = Object.assign({}, defaultOptions, userOptions);



  const styleLoader = {

    loader: require.resolve('style-loader'),

    options: options.style,

  };



  const cssLoader = {

    loader: require.resolve('css-loader'),

    options: options.css[constantEnv],

  };



  const resolveUrlLoader = {

    loader: require.resolve('resolve-url-loader'),

    options: options.resolveUrl[constantEnv],

  };



  const postCssLoader = {

    loader: require.resolve('postcss-loader'),

    options: Object.assign({}, options.postcss[constantEnv], {

      plugins: () => options.postcss.plugins,

    }),

  };



  const sassLoader = {

    loader: require.resolve('sass-loader'),

    options: options.sass[constantEnv]

  };



  config.module.rules = [

    ...config.module.rules,

    {

      test: /\.(sa|sc)ss$/,

      use: isServer

        ? [

            {

              loader: require.resolve('css-loader/locals'),

              options: options.css[constantEnv],

            },

            sassLoader

          ]

        : [

            dev ? styleLoader : MiniCssExtractPlugin.loader,

            cssLoader,

            resolveUrlLoader,

            postCssLoader,

            sassLoader,

          ],

    },

  ];



  return config;

};
```

**Comment by IanBarbour** [comment]
Can anybody help with this?

**Comment by vget98** [comment]
I am having this problem too
