### ISSUE TITLE
Isuue in running razzle with Typescript

### ISSUE THREAD

**Issue by kirankalyan5** [jaredpalmer/razzle#984]
I followed all the steps for razzle typescript but unable to run the project.

ERROR

```
{ Error: Cannot find module 'tslint'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:613:15)
    at Function.Module._load (internal/modules/cjs/loader.js:539:25)
    at Module.require (internal/modules/cjs/loader.js:667:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at new ForkTsCheckerWebpackPlugin (/Users/kkk/Documents/work/frontend/node_modules/fork-ts-checker-webpack-plugin/lib/index.js:85:15)
    at modify (/Users/kkk/Documents/work/frontend/node_modules/razzle-plugin-typescript/index.js:67:7)
    at runPlugin (/Users/kkk/Documents/work/frontend/node_modules/razzle/config/runPlugin.js:26:10)
    at runPlugin (/Users/kkk/Documents/work/frontend/node_modules/razzle/config/runPlugin.js:6:12)
    at plugins.forEach.plugin (/Users/kkk/Documents/work/frontend/node_modules/razzle/config/createConfig.js:549:16)
    at Array.forEach (<anonymous>)
    at module.exports (/Users/kkk/Documents/work/frontend/node_modules/razzle/config/createConfig.js:548:13)
    at main (/Users/*/Documents/work/*/node_modules/razz/node_modules/razzle/scripts/start.js:47:22)
    at processTicksAndRejections (internal/process/next_tick.js:81:5) code: 'MODULE_NOT_FOUND' }
✨  Done in 2.24s.
```

Not sure if I'm missing something.

Also, the example works fine! the only difference I find is the package versions.

FYR - My package versions

```
"dependencies": {
    "express": "^4.16.4",
    "razzle": "^3.0.0",
    "react": "^16.8.6",
    "react-dom": "^16.8.6",
    "react-router-dom": "^5.0.0"
  },
  "devDependencies": {
    "@types/express": "^4.16.1",
    "@types/jest": "^24.0.11",
    "@types/react": "^16.8.13",
    "@types/react-dom": "^16.8.4",
    "@types/react-router-dom": "^4.3.2",
    "@types/webpack-env": "^1.13.9",
    "razzle-plugin-typescript": "^3.0.0",
    "ts-jest": "^24.0.2",
    "ts-lint": "^4.5.1",
    "tslint-react": "^4.0.0",
    "typescript": "^3.4.3"
  },
```
Appreciate the help!

**Comment by alexbechmann** [comment]
@kirankalyan5 I think you need to install “tslint” instead ”ts-lint”.

**Comment by kirankalyan5** [comment]
@alexbechmann good catch, Got it working 😁
Thanks
